### ISSUE TITLE
Drop some configuration options

### ISSUE THREAD

**Issue by stwalkerster** [enwikipedia-acc/waca#104]
In order to simplify the code of the tool, we could drop a few configuration options that AFAIK we don't ever change and have become so ingrained that disabling them would be unintuitive or break things.

* [x] $enableRenames = 1
* [x] $protectReservedRequests = true
* [x] $enableAdminBreakReserve = true
* [x] $enableCommentEditing = 1

* [x] $allowViewingOfUseragent = 1

**Comment by JohnFLewis** [comment]
Removed all variables and pushed to master. Work on local install and on dev with the checks removed.
