### ISSUE TITLE
Improve the API to be able to query stats by wikiusername

### ISSUE THREAD

**Issue by Technical-13** [enwikipedia-acc/waca#127]
Improve the API to be able to query stats by wikiusername for people like John who have different names in the tool and onwiki... :whale:

**Comment by stwalkerster** [comment]
Due to OAuth and the fact we no longer store the on-wiki username, this could suffer from major performance issues. We probably want a sensible way of caching that data anyway.

**Comment by stwalkerster** [comment]
Thrown to newinternal/on hold - this will need to wait for #265 first, after which it will become easy.
