### ISSUE TITLE
Request already reserved by $1

### ISSUE THREAD

**Issue by Technical-13** [enwikipedia-acc/waca#138]
This message would be better served as a alert on the "requests" page where acknowledgment reloads the page with an updated list to see what is available without having to navigate away and use the "back" button or the "requests" button on the top of the page.  Would save time on page loads.  Similar to #128 and I see no user config for either.

**Comment by stwalkerster** [comment]
This is in `/includes/Pages/RequestAction/PageReservation.php`, and it's possible we could trap the ALEs and treat them as a redirect, but remember that this can be triggered from both the request list pages and the view request page.

We need to decide if we want to fix this, and if so, how.

**Comment by dqwiki** [comment]
I'm not a fan of this idea. It seems like this would just encourage faster user processing. We already want people to slow down so errors don't occur, and I think separation and different nav are important.

**Comment by stwalkerster** [comment]
Closing per DQ
