### ISSUE TITLE
When viewing a request details, page title should include id

### ISSUE THREAD

**Issue by Technical-13** [enwikipedia-acc/waca#143]
When `?action=zoom&id=#######` then the title should be `<title>####### - English Wikipedia Internal Account Creation Interface</title>` so that it will be easier to note which ticket on IRC if asking for help without having to tab flip back and forth.

**Comment by stwalkerster** [comment]
Depends on #232

**Comment by stwalkerster** [comment]
Fixed in newinternal branch
