### ISSUE TITLE
Decode htmlentities in emails and logs

### ISSUE THREAD

**Issue by Technical-13** [enwikipedia-acc/waca#144]
It's real annoying (and I'm sure confusing to new users) to see escaped entities in emails and in the logs on the requests... I understand escaping for the purpose of the database, but these things should be decoded before being displayed and sent in emails.  I'm assuming that we are throwing them in the db with http://us2.php.net/manual/en/function.htmlentities.php and as such, when we pull them back out we should be using http://us2.php.net/html_entity_decode

**Comment by stwalkerster** [comment]
Fixed in newinternal
