### ISSUE TITLE
Created accounts show up as AntiSpoof accounts

### ISSUE THREAD

**Issue by cyberpower678** [enwikipedia-acc/waca#162]
They used to say the account was already created.  Since it has the handy password reset button.  I propose making it say the account exists rather than list it under AntiSpoof results, and also have it show the password reset button.  I always get misled when I look at that.  And sometimes, AntiSpoof results don't show up.

**Comment by FunPika** [comment]
Looks like results not showing up is now #212. As far as @Technical-13's comment goes, that should be done as a separate issue.
