### ISSUE TITLE
Move the ACC number request to new spot in email subject line

### ISSUE THREAD

**Issue by dqwiki** [enwikipedia-acc/waca#174]
Currently we have [ACC #XXXXX] English Wikipedia Account Request. This screws with gmail and makes it group all conversations together. I really don't care about the new end subject line, but can we please remove the brackets around ACC# ?

**Comment by stwalkerster** [comment]
Any consensus on this?

**Comment by cyberpower678** [comment]
I think it's fine the way it is.

**Comment by Matthewrbowker** [comment]
I also think it's fine the way it is.

**Comment by stwalkerster** [comment]
I'll just close this then.
