### ISSUE TITLE
Link to Special:CheckUserLog

### ISSUE THREAD

**Issue by Callanecc** [enwikipedia-acc/waca#179]
Could a link to the CU log be added to the of the collection of links for IPs. I use it fairly regularly to work out what the intended target of the block is, and usually as one of the things I check before clicking the button on Special:CheckUser.

@dqwiki specifically what do you think?

**Comment by stwalkerster** [comment]
https://en.wikipedia.org/wiki/Special:CheckUserLog?cuSearchType=target&cuSearch=127.0.0.1  ?

**Comment by stwalkerster** [comment]
Relevant file is here: https://github.com/enwikipedia-acc/waca/blob/master/templates/zoom-parts/ip-links.tpl

**Comment by Callanecc** [comment]
https://en.wikipedia.org/wiki/Special:CheckUserLog?cuSearchType=target&cuSearch=127.0.0.1 is the correct link, yes.

**Comment by dqwiki** [comment]
@Callanecc Ya, I would use it too, not a bad idea.
