### ISSUE TITLE
"unknown" XFF address

### ISSUE THREAD

**Issue by FunPika** [enwikipedia-acc/waca#182]
See https://accounts.wmflabs.org/acc.php?action=zoom&id=141848, which has an "unknown" address in the XFF header.

Not exactly sure how we should handle these at the moment (maybe just remove the links as if it were a trusted address?), but there is no real point in showing users links to information related to User:Unknown here.

**Comment by stwalkerster** [comment]
Actual XFF header contains `unknown, 1.1.1.1, 2.2.2.2` (data sanitised for privacy), with IP `10.68.16.65` (internal proxy). We should actually parse the IPs individually, and sanity check that each is an IP address, remembering to check IPv4 and v6 addresses.

It's my preference to add a new option to the proxy array, which marks it as an errored IP, and pass in the error reason. [This is the template](https://github.com/enwikipedia-acc/waca/blob/master/templates/zoom-parts/ip-section.tpl#L14). 

`{if $proxy.error}` Trust label should probably be "failed" (red), then the rest of the rows should be colspan'd together with `{$proxy.errormessage}`.

[In the code behind](https://github.com/enwikipedia-acc/waca/blob/master/zoompage.php#L119), we should attempt a parse of the IP, and set those two array keys as appropriate, as well as revoking trust for the rest of the chain?

Does this sound like a reasonable fix?

Also, while someone's there, can the whitespace be fixed? Right now, GitHub is interpreting the mismatch of tabs/spaces and messing it all up. :cry: We probably ought to agree on a standard anyway.

**Comment by FunPika** [comment]
I just dealt with the whitespace using Scrutinizer (from my fork, since I don't have access to apply its patches directly to here). At least for now, everything in zoompage.php is tab indented.

**Comment by stwalkerster** [comment]
Fixed (discarded) by @FastLizard4 in #465

**Comment by FastLizard4** [comment]
@stwalkerster Do we actually want to close this?  IIRC, you wanted to come up with a better way of handling this in newinternal
