### ISSUE TITLE
Create coding style guide and stick to it

### ISSUE THREAD

**Issue by FunPika** [enwikipedia-acc/waca#184]
Following up on a comment @stwalkerster left on #182, we should really agree on a standard way of indenting lines. Once we do this, we should go through all of the code and make sure it uses that standard (Scrutinizer can probably do this automatically).

I personally would prefer to use [MediaWiki's tab style] (https://www.mediawiki.org/wiki/Manual:Coding_conventions#Tab_size), which is one hard tab per indentation level.

**Comment by stwalkerster** [comment]
I think we're there in #232, so will close for now
