### ISSUE TITLE
Add defer to hold checkbox for custom closes.

### ISSUE THREAD

**Issue by cyberpower678** [enwikipedia-acc/waca#188]
When a request gets put on hold, an email usually gets sent out to the requester.  It would be great to simply be able to check a box that defers to hold instead of closes when an email gets sent out from the interface.

**Comment by stwalkerster** [comment]
So, the way I foresee this happening is more along the lines of adding the ability to send an email to a requestor without closing the request. I think the cleanest way of implementing this (within existing functionality and with what people expect to see) is to replace that "Account Created" checkbox on the custom close form with something like this (quickly thrown together with browser developer tools):

![image](https://cloud.githubusercontent.com/assets/722710/8071935/ce51d1d0-0f06-11e5-84e6-6783b7381fbc.png)

Opinions?

**Comment by cyberpower678** [comment]
Yes please.

**Comment by cyberpower678** [comment]
I still feel this to be a useful feature.  It would save me the effort of cluttering up the log entries, just to keep the information together and more searchable.

**Comment by stwalkerster** [comment]
Deployed to the sandbox, will need to be *extensively* tested before pushing to production given how much of the code I ended up touching with this
