### ISSUE TITLE
Declining requests gives undefined variable notice

### ISSUE THREAD

**Issue by stwalkerster** [enwikipedia-acc/waca#194]
Notice: Undefined variable: comment in
/data/project/application/production/includes/DataObjects/User.php on
line 541

Reported by DocTree on mailing list

**Comment by stwalkerster** [comment]
@FastLizard4 - you've declined users recently - have you seen this? Has it been fixed already?

**Comment by FastLizard4** [comment]
@stwalkerster Nope, can't recall seeing this message in recent memory

**Comment by stwalkerster** [comment]
can't reproduce either.
