### ISSUE TITLE
Force HTTPS on acc.php

### ISSUE THREAD

**Issue by Matthewrbowker** [enwikipedia-acc/waca#199]
Currently, the acc.php page is accessible via HTTP or HTTPS.  For security, recommend forcing HTTPS via server-side directives.

**Comment by stwalkerster** [comment]
I can't reproduce this :confused:

**Comment by Matthewrbowker** [comment]
This is what I am seeing:
<img width="367" alt="screen shot 2015-11-02 at 11 37 20" src="https://cloud.githubusercontent.com/assets/802331/10890622/2c470b2c-8156-11e5-925e-54725e96e712.png">

http://accounts.wmflabs.org/acc.php

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0 ID:20151102030241 CSet: 451a185791433bce1a6a894c27f3da60a3119431

**Comment by stwalkerster** [comment]
Dang. HTTPS Everywhere is awesome, except when debugging HTTPS issues... :unamused:
