### ISSUE TITLE
Suspension reasons are no longer shown in the log

### ISSUE THREAD

**Issue by FastLizard4** [enwikipedia-acc/waca#203]
It seems that for suspensions made after a certain date, the reason is no longer shown in any log that I can see, and I can't find the code responsible.

**Comment by stwalkerster** [comment]
Looks like it's the actual suspension code at fault here.


Op do 26 nov. 2015 07:12 schreef FastLizard4 <notifications@github.com>:

**Comment by FastLizard4** [comment]
Got your screenshot.  Taking a look now, I'll see what I can do.

**Comment by stwalkerster** [comment]
Having had a quick glance through the suspension code, I can't see anything obvious. May need to throw a debugger on it :/

**Comment by FastLizard4** [comment]
Yeah, everything looks correct from User.php to the logging code.  Not sure what's going on.,

**Comment by stwalkerster** [comment]
I wonder if this is something that's already been fixed in master but not deployed to production yet - prod is running rel6.7.2 right now, and I've been hesitant to deploy the both security sensitive and schema changes that are in place at the moment.

**Comment by FastLizard4** [comment]
I just looked through the rel6.7.2 code, and it looks identical.  No problems anywhere I can see.  I'm stumped.  :\
