### ISSUE TITLE
Better handling of a non-existant database

### ISSUE THREAD

**Issue by Matthewrbowker** [enwikipedia-acc/waca#205]
If the database doesn't exist, we throw an exception that is never caught.  Catching an exception and displaying a nice page is very helpful.

**Comment by jackkyyy** [comment]
ok

**Comment by jackkyyy** [comment]
ok

**Comment by jackkyyy** [comment]
205

**Comment by stwalkerster** [comment]
@jackkyyy ???

**Comment by stwalkerster** [comment]
Current configuration means that the skin depends on being able to load a user from the database. If the database is down, all hell breaks loose.

**Comment by stwalkerster** [comment]
Fixed in #232
