### ISSUE TITLE
Add create and close button

### ISSUE THREAD

**Issue by cyberpower678** [enwikipedia-acc/waca#207]
With accounts now tied to OAuth, having the options in settings to replace the big blue button with a blue and a green button would be nice.  The blue button is create account, and the green button is create and close with an identical drop down to the close created request button.  In addition, an additional checkbox, for custom closing is available, "Create account" which also create the account, and automatically mark the "account created" checkbox.

Error handling is required.  When the account process fails, it should throw a warning on the top of the request, and leave the request open and reserved, and preferably the create and close button gets greyed out.

**Comment by stwalkerster** [comment]
If memory serves, this is blocked at the moment by some missing functionality on the API - not sure if that is still the case though.

**Comment by cyberpower678** [comment]
Like what.  It's been possible to create accounts via the API, and it's easy to setup OAuth API calls.

**Comment by cyberpower678** [comment]
Combine the two.

**Comment by stwalkerster** [comment]
Yes, standard API createaccount I think is fine. The problems lie in antispoof and titleblacklist I believe, possibly SUL too. It's not just a simple job of getting the tool to do the account creation like you make it out to be. I'll take another look at this when I'm back at home from visiting family

**Comment by cyberpower678** [comment]
Well with those, the account should be created manually anyway.  The tool looks for a success or fail response.

Gesendet von Maximilian's iPhone. 
(Sent from Maximilian's iPhone.)

**Comment by FunPika** [comment]
The API does have ignoreantispoof and ignoretitleblacklist parameters now.

**Comment by cyberpower678** [comment]
Perhaps I can work on integrating OAuth into the interface more fluently.  He claims it's slow, but I've been getting speedy responses from it.

**Comment by FunPika** [comment]
Just going to note that if anyone actually does this, they should probably take care of #141 while they're at it. ;)

**Comment by mdaniels5757** [comment]
I know you just closed this, but there could be a problem: antispoof sometimes doesn't catch things. We really shouldn't do this when #212 is still open (and I have experienced 212 myself recently).

**Comment by stwalkerster** [comment]
#212 refers to the in-tool detection of spoofs.

If you try and create an account with an antispoof hit, whether it's detected or not, the autocreation code will vomit and chuck it back to the tool users for manual creation. It's not smart enough to handle antispoof hits or title blacklist hits. #212 is a pain, but I don't think it's actually an issue for this task.

**Comment by stwalkerster** [comment]
(For a more technical explanation, the autocreation code doesn't ever check the "override spoof check" or the "override title blacklist" checkboxes, thus MediaWiki itself prevents the creation. The error is detected, and the request thrown back)

**Comment by mdaniels5757** [comment]
Ah, ok.
