### ISSUE TITLE
Look into changing request comment to TEXT

### ISSUE THREAD

**Issue by stwalkerster** [enwikipedia-acc/waca#209]
So, it's currently a LONGTEXT, which is 2^32 -1 bytes (4 GB max of text). This is excessive.

Can we fit all existing data in a TEXT (2^16 -1 = 65535 bytes)?

**Comment by stwalkerster** [comment]
I'm looking at reducing this to 3000 chars - which is approximately equivalent to the highlighted text:

![image](https://cloud.githubusercontent.com/assets/722710/12072312/93e960e6-b0d0-11e5-94ab-407843fc249d.png)

Does this seem long enough?

Note that there are 36 requests in the production system which exceed this length, which will be truncated by this change. All of them appear to fall broadly into these categories:

1. Full page (main page, request form, account creation form, block notice) copy/paste into comment box
1. Spam (potato potato potato ..., "our services include...")
1. Essay about what's wrong with Wikipedia, biography
1. Foreign-language content which I can't read

**Comment by stwalkerster** [comment]
(that's 36 / 103885  == 0.03%)

**Comment by cyberpower678** [comment]
I'd like to see those requests. :p

**Comment by cyberpower678** [comment]
3000 is more than enough.  I'd argue 1000 is perfectly sufficient.  I don't want to read essays for requests.

**Comment by stwalkerster** [comment]
1k would truncate 185 requests, including useful data in some of those comments (blocked username, for instance).
