### ISSUE TITLE
"Deferred to admins" comment when deferring a request to Flagged Users

### ISSUE THREAD

**Issue by MJ94** [enwikipedia-acc/waca#215]
When I deferred request 160196 to Flagged Users today, the comment log marked it as "deferred to admins." This should say "deferred to flagged users," correct? Many flagged users are not tool administrators.

**Comment by cyberpower678** [comment]
That log entry probably goes back to the time when accounts creators didn't exist as a right, so admins had to do the overriding of limits and spoofs.

Gesendet von Maximilian's iPhone. 
(Sent from Maximilian's iPhone.)

**Comment by MJ94** [comment]
I'm referring to the tool comment log, not any log on Wikipedia.

**Comment by cyberpower678** [comment]
Yea I meant that too.  Sorry. 

Gesendet von Maximilian's iPhone. 
(Sent from Maximilian's iPhone.)

**Comment by FastLizard4** [comment]
So, the problem here is in the ACC configuration, actually:

```php
$availableRequestStates = array(
	// ...
	'Admin'=>array(
		'defertolog' => 'admins', // don't change or you'll break old logs
		'deferto' => 'flagged users',
		'header' => 'Flagged user needed',
		'api' => "admin",
		),
	// ...
);
```

It's the `'defertolog' => 'admins'` that's causing this problem.  Unfortunately, as noted, one can't change the defertolog option without breaking old logs.  So fixing this will probably involve doing some database modifications.

Paging @stwalkerster!

**Comment by FastLizard4** [comment]
Looks like, at minimum, changing the 'defertolog' value will necessitate this query:

```sql
UPDATE `log`
SET `action`='Deferred to flagged users'
WHERE `action`='Deferred to admins';
```

**Comment by FastLizard4** [comment]
Upon further review of the ACC code, I think changing the 'defertolog' value should actually be pretty safe - it should just be a matter of changing the value in config, then running the above database query.

**Comment by FastLizard4** [comment]
So, this seemed to work fine in my local development environment.  Of course, that's a far cry from production... but at least that means this should be doable.  What do you think, @stwalkerster?

**Comment by stwalkerster** [comment]
Change `config.inc.php` (tool config doesn't override that setting), and create a DB patch with @FastLizard4 's query and you're done. :grinning:

**Comment by stwalkerster** [comment]
While you're at it, it might be an idea to change the array key of that entry too, and add another DB change:

```sql
UPDATE request
SET status = 'Flagged users'
WHERE status = 'Admin';
```

To test, you'll need some requests deferred to flagged users, verify they stay deferred to flagged users after the change.

**Comment by stwalkerster** [comment]
(This is literally a config change and a patch file to be created with two statements already written here - hence +easy :stuck_out_tongue: )

**Comment by FastLizard4** [comment]
But if there's one thing I learned, it's that anything that touches the production database isn't easy.  :P

**Comment by stwalkerster** [comment]
@FastLizard4 :grinning:

It'll likely be me that deploys anything anyway and therefore have to fix, whatcha worried about? :wink:

**Comment by FastLizard4** [comment]
@stwalkerster I like how it ended up being me deploying this anyway.  :P
