### ISSUE TITLE
Feature request: Larger "Other requests from $IP" information

### ISSUE THREAD

**Issue by Tiggerjay** [enwikipedia-acc/waca#216]
Just a feature request to perhaps display a subnet/CIDR for the "other requests from IP" to evaluate multiple requests coming from the same network. Could be something small like / 28, or perhaps larger such as / 24... 

Another thought, although it would be more work, would be to consider sending a query to ARIN for the CIDR of that specific network, and then displaying all incoming requests from that range. (such as using https://github.com/addiscent/ip-addr-to-arin-cidr) For performance, I would imagine quering ARIN at request creation, but then for accuracy displaying actual "other request" data live at time of viewing/handling the request. Also to minimize performance drain would be to limit the subnet to no larger than /24, and perhaps the prior 10 requests. 

Just my 2 cents.

**Comment by dqwiki** [comment]
> Another thought, although it would be more work, would be to consider sending a query to ARIN for the CIDR of that specific network, and then displaying all incoming requests from that range. (such as using https://github.com/addiscent/ip-addr-to-arin-cidr) For performance, I would imagine quering ARIN at request creation, but then for accuracy displaying actual "other request" data live at time of viewing/handling the request. Also to minimize performance drain would be to limit the subnet to no larger than /24, and perhaps the prior 10 requests.

This *may* be a way forward. Original thought was declined in PR.

**Comment by stwalkerster** [comment]
Going to decline as this has privacy implications and the RIR query approach is probably more effort than it's worth.
