### ISSUE TITLE
SUL redirect hung

### ISSUE THREAD

**Issue by Tiggerjay** [enwikipedia-acc/waca#218]
Clicking the SUL Tool never properly redirects to CentralAuth. Also checked with TaqPol in IRC and he is also having the same issue. I think it's new since the 6.8 release?

**Comment by Tiggerjay** [comment]
Hmm, no longer an issue.

**Comment by stwalkerster** [comment]
I love it when problems just disappear :grinning:

**Comment by Tiggerjay** [comment]
Yeah, not sure if it's good or not. :) May have been an upstream issue.
Although the tool does appear to be running a bit slow today as well.

On Mon, Jan 11, 2016 at 12:08 PM, Simon Walker <notifications@github.com>
wrote:

> I love it when problems just disappear [image: :grinning:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/enwikipedia-acc/waca/issues/218#issuecomment-170674375>
> .
>



-- 
Jason
http://en.wikipedia.org/wiki/User:Tiggerjay
Account Creation Team
