### ISSUE TITLE
The Devs

### ISSUE THREAD

**Issue by MJ94** [enwikipedia-acc/waca#229]
see title

**Comment by FastLizard4** [comment]
I agree.  The devs need to be rewritten as soon as possible.

**Comment by MJ94** [comment]
**#SOS**

**Comment by FastLizard4** [comment]
(Unfortunately, this is a bit of an upstream issue; might take some time to get resolved)

**Comment by MJ94** [comment]
halp

**Comment by stwalkerster** [comment]
I believe this is an issue with the current configuration too, +live config
