### ISSUE TITLE
Check if a request being created does not already exist; Reverts back to main page

### ISSUE THREAD

**Issue by RileyHuntley** [enwikipedia-acc/waca#247]
Upon hitting "no" button, return to request instead of main page. The point of this is because if someone goes to hit "created" but hasn't yet created the account, they are going to want to return to the request to create the account. Or if it was an accidental click and they meant to close as something else, they'll still want to return to the request.

 [Relevant code](https://github.com/enwikipedia-acc/waca/blob/341541e6720b26421d018e7d7ecf48cd39e95adf/acc.php#L1193)

**Comment by FastLizard4** [comment]
This isn't a very serious issue, so I'd aim for resolving this in newinternal.  Ping #232.

**Comment by stwalkerster** [comment]
Fixed in #232
