### ISSUE TITLE
Tool down

### ISSUE THREAD

**Issue by RileyHuntley** [enwikipedia-acc/waca#249]
Tool has been down since 3:00AM Friday UTC, sandbox down as well.

**Comment by stwalkerster** [comment]
DB instance is in SHUTOFF state, not sure why.

**Comment by FastLizard4** [comment]
I sent an email to the Labs mailing list asking for assistance from the Labs admins.  The instance providing MySQL seems to be stuck in the SHUTOFF state.  Simon and I have both been unable to reboot it, so now we're waiting on the Labs admins to get back to us.

**Comment by stwalkerster** [comment]
Andrew Boggott has restarted the instance, tool seems back up.

**Comment by Matthewrbowker** [comment]
Appears to be back up.  Closing.
