### ISSUE TITLE
Runkit not installing for unit tests on PHP7

### ISSUE THREAD

**Issue by Matthewrbowker** [enwikipedia-acc/waca#253]
Log is included below, it appears runkit is unable to install.  Filing for investigation and possible push upstream

> 
> downloading
> 
>  runkit-1.0.4.tgz ...
> 
> Starting to download runkit-1.0.4.tgz (103,274 bytes)
> 
> ........................done: 103,274 bytes
> 
> 17 source files, building
> 
> running: phpize
> 
> Configuring for:
> 
> PHP Api Version:         20151012
> 
> Zend Module Api No:      20151012
> 
> Zend Extension Api No:   320151012
> 
> building in /tmp/pear/install/pear-build-travisIYi8B6/runkit-1.0.4
> 
> running: /tmp/pear/install/runkit/configure --with-php-config=/home/travis/.phpenv/versions/7.0.4/bin/php-config
> 
> checking for grep that handles long lines and -e... /bin/grep
> 
> checking for egrep... /bin/grep -E
> 
> checking for a sed that does not truncate output... /bin/sed
> 
> checking for cc... cc
> 
> checking whether the C compiler works... yes
> 
> checking for C compiler default output file name... a.out
> 
> checking for suffix of executables...
> 
> checking whether we are cross compiling... no
> 
> checking for suffix of object files... o
> 
> checking whether we are using the GNU C compiler... yes
> 
> checking whether cc accepts -g... yes
> 
> checking for cc option to accept ISO C89... none needed
> 
> checking how to run the C preprocessor... cc -E
> 
> checking for icc... no
> 
> checking for suncc... no
> 
> checking whether cc understands -c and -o together... yes
> 
> checking for system library directory... lib
> 
> checking if compiler supports -R... no
> 
> checking if compiler supports -Wl,-rpath,... yes
> 
> checking build system type... x86_64-unknown-linux-gnu
> 
> checking host system type... x86_64-unknown-linux-gnu
> 
> checking target system type... x86_64-unknown-linux-gnu
> 
> checking for PHP prefix... /home/travis/.phpenv/versions/7.0.4
> 
> checking for PHP includes... -I/home/travis/.phpenv/versions/7.0.4/include/php -I/home/travis/.phpenv/versions/7.0.4/include/php/main -I/home/travis/.phpenv/versions/7.0.4/include/php/TSRM -I/home/travis/.phpenv/versions/7.0.4/include/php/Zend -I/home/travis/.phpenv/versions/7.0.4/include/php/ext -I/home/travis/.phpenv/versions/7.0.4/include/php/ext/date/lib
> 
> checking for PHP extension directory... /home/travis/.phpenv/versions/7.0.4/lib/php/extensions/no-debug-zts-20151012
> 
> checking for PHP installed headers prefix... /home/travis/.phpenv/versions/7.0.4/include/php
> 
> checking if debug is enabled... no
> 
> checking if zts is enabled... yes
> 
> checking for re2c... re2c
> 
> checking for re2c version... 0.13.5 (ok)
> 
> checking for gawk... gawk
> 
> checking whether to enable runkit support... yes, shared
> 
> checking wheter to enable runtime manipulation of functions/classes/constants... inherit
> 
> checking whether to enable registration of user-defined autoglobals... inherit
> 
> checking whether to enable Sandbox support... inherit
> 
> checking for ld used by cc... /usr/bin/ld
> 
> checking if the linker (/usr/bin/ld) is GNU ld... yes
> 
> checking for /usr/bin/ld option to reload object files... -r
> 
> checking for BSD-compatible nm... /usr/bin/nm -B
> 
> checking whether ln -s works... yes
> 
> checking how to recognize dependent libraries... pass_all
> 
> checking for ANSI C header files... yes
> 
> checking for sys/types.h... yes
> 
> checking for sys/stat.h... yes
> 
> checking for stdlib.h... yes
> 
> checking for string.h... yes
> 
> checking for memory.h... yes
> 
> checking for strings.h... yes
> 
> checking for inttypes.h... yes
> 
> checking for stdint.h... yes
> 
> checking for unistd.h... yes
> 
> checking dlfcn.h usability... yes
> 
> checking dlfcn.h presence... yes
> 
> checking for dlfcn.h... yes
> 
> checking the maximum length of command line arguments... 1572864
> 
> checking command to parse /usr/bin/nm -B output from cc object... ok
> 
> checking for objdir... .libs
> 
> checking for ar... ar
> 
> checking for ranlib... ranlib
> 
> checking for strip... strip
> 
> checking if cc supports -fno-rtti -fno-exceptions... no
> 
> checking for cc option to produce PIC... -fPIC
> 
> checking if cc PIC flag -fPIC works... yes
> 
> checking if cc static flag -static works... yes
> 
> checking if cc supports -c -o file.o... yes
> 
> checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
> 
> checking whether -lc should be explicitly linked in... no
> 
> checking dynamic linker characteristics... GNU/Linux ld.so
> 
> checking how to hardcode library paths into programs... immediate
> 
> checking whether stripping libraries is possible... yes
> 
> checking if libtool supports shared libraries... yes
> 
> checking whether to build shared libraries... yes
> 
> checking whether to build static libraries... no
> 
> creating libtool
> 
> appending configuration tag "CXX" to libtool
> 
> configure: creating ./config.status
> 
> config.status: creating config.h
> 
> running: make
> 
> /bin/bash /tmp/pear/install/pear-build-travisIYi8B6/runkit-1.0.4/libtool --mode=compile cc -Wdeclaration-after-statement -Werror -Wall -Wno-deprecated-declarations -I. -I/tmp/pear/install/runkit -DPHP_ATOM_INC -I/tmp/pear/install/pear-build-travisIYi8B6/runkit-1.0.4/include -I/tmp/pear/install/pear-build-travisIYi8B6/runkit-1.0.4/main -I/tmp/pear/install/runkit -I/home/travis/.phpenv/versions/7.0.4/include/php -I/home/travis/.phpenv/versions/7.0.4/include/php/main -I/home/travis/.phpenv/versions/7.0.4/include/php/TSRM -I/home/travis/.phpenv/versions/7.0.4/include/php/Zend -I/home/travis/.phpenv/versions/7.0.4/include/php/ext -I/home/travis/.phpenv/versions/7.0.4/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/pear/install/runkit/runkit.c -o runkit.lo
> 
> mkdir .libs
> 
>  cc -Wdeclaration-after-statement -Werror -Wall -Wno-deprecated-declarations -I. -I/tmp/pear/install/runkit -DPHP_ATOM_INC -I/tmp/pear/install/pear-build-travisIYi8B6/runkit-1.0.4/include -I/tmp/pear/install/pear-build-travisIYi8B6/runkit-1.0.4/main -I/tmp/pear/install/runkit -I/home/travis/.phpenv/versions/7.0.4/include/php -I/home/travis/.phpenv/versions/7.0.4/include/php/main -I/home/travis/.phpenv/versions/7.0.4/include/php/TSRM -I/home/travis/.phpenv/versions/7.0.4/include/php/Zend -I/home/travis/.phpenv/versions/7.0.4/include/php/ext -I/home/travis/.phpenv/versions/7.0.4/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /tmp/pear/install/runkit/runkit.c  -fPIC -DPIC -o .libs/runkit.o
> 
> In file included from /tmp/pear/install/runkit/runkit.c:22:0:
> 
> /tmp/pear/install/runkit/php_runkit.h: In function ‘php_runkit_modify_function_doc_comment’:
> 
> /tmp/pear/install/runkit/php_runkit.h:320:29: error: assignment from incompatible pointer type [-Werror]
> 
> /tmp/pear/install/runkit/php_runkit.h:321:16: error: ‘zend_op_array’ has no member named ‘doc_comment_len’
> 
> /tmp/pear/install/runkit/php_runkit.h: In function ‘PHP_RUNKIT_ADD_MAGIC_METHOD’:
> 
> /tmp/pear/install/runkit/php_runkit.h:462:17: error: ‘zend_class_entry’ has no member named ‘name_length’
> 
> /tmp/pear/install/runkit/php_runkit.h:463:26: error: ‘zend_class_entry’ has no member named ‘name_length’
> 
> /tmp/pear/install/runkit/php_runkit.h:463:26: error: ‘zend_class_entry’ has no member named ‘name_length’
> 
> /tmp/pear/install/runkit/php_runkit.h:463:26: error: ‘zend_class_entry’ has no member named ‘name_length’
> 
> /tmp/pear/install/runkit/php_runkit.h:463:26: error: ‘zend_class_entry’ has no member named ‘name_length’
> 
> /tmp/pear/install/runkit/php_runkit.h:463:26: error: ‘zend_class_entry’ has no member named ‘name_length’
> 
> /tmp/pear/install/runkit/php_runkit.h:463:26: error: ‘zend_class_entry’ has no member named ‘name_length’
> 
> /tmp/pear/install/runkit/php_runkit.h:463:26: error: ‘zend_class_entry’ has no member named ‘name_length’
> 
> /tmp/pear/install/runkit/php_runkit.h:463:26: error: ‘zend_class_entry’ has no member named ‘name_length’
> 
> /tmp/pear/install/runkit/php_runkit.h:463:26: error: ‘zend_class_entry’ has no member named ‘name_length’
> 
> /tmp/pear/install/runkit/php_runkit.h:463:26: error: ‘zend_class_entry’ has no member named ‘name_length’
> 
> /tmp/pear/install/runkit/php_runkit.h:463:26: error: ‘zend_class_entry’ has no member named ‘name_length’
> 
> /tmp/pear/install/runkit/php_runkit.h:463:26: error: ‘zend_class_entry’ has no member named ‘name_length’
> 
> /tmp/pear/install/runkit/php_runkit.h:463:26: error: ‘zend_class_entry’ has no member named ‘name_length’
> 
> /tmp/pear/install/runkit/php_runkit.h:463:26: error: ‘zend_class_entry’ has no member named ‘name_length’
> 
> /tmp/pear/install/runkit/php_runkit.h:463:26: error: ‘zend_class_entry’ has no member named ‘name_length’
> 
> /tmp/pear/install/runkit/php_runkit.h:463:26: error: ‘zend_class_entry’ has no member named ‘name_length’
> 
> /tmp/pear/install/runkit/php_runkit.h:463:26: error: ‘zend_class_entry’ has no member named ‘name_length’
> 
> /tmp/pear/install/runkit/php_runkit.h:463:26: error: ‘zend_class_entry’ has no member named ‘name_length’
> 
> /tmp/pear/install/runkit/php_runkit.h:463:26: error: ‘zend_class_entry’ has no member named ‘name_length’
> 
> /tmp/pear/install/runkit/php_runkit.h:463:26: error: ‘zend_class_entry’ has no member named ‘name_length’
> 
> /tmp/pear/install/runkit/php_runkit.h:463:26: error: ‘zend_class_entry’ has no member named ‘name_length’
> 
> /tmp/pear/install/runkit/php_runkit.h:463:26: error: ‘zend_class_entry’ has no member named ‘name_length’
> 
> /tmp/pear/install/runkit/php_runkit.h:463:26: error: ‘zend_class_entry’ has no member named ‘name_length’
> 
> /tmp/pear/install/runkit/php_runkit.h:463:26: error: ‘zend_class_entry’ has no member named ‘name_length’
> 
> /tmp/pear/install/runkit/php_runkit.h:463:26: error: ‘zend_class_entry’ has no member named ‘name_length’
> 
> /tmp/pear/install/runkit/php_runkit.h:463:26: error: ‘zend_class_entry’ has no member named ‘name_length’
> 
> /tmp/pear/install/runkit/php_runkit.h:463:26: error: ‘zend_class_entry’ has no member named ‘name_length’
> 
> /tmp/pear/install/runkit/php_runkit.h:463:26: error: ‘zend_class_entry’ has no member named ‘name_length’
> 
> /tmp/pear/install/runkit/php_runkit.h:463:26: error: ‘zend_class_entry’ has no member named ‘name_length’
> 
> /tmp/pear/install/runkit/php_runkit.h:463:26: error: ‘zend_class_entry’ has no member named ‘name_length’
> 
> /tmp/pear/install/runkit/php_runkit.h:463:26: error: ‘zend_class_entry’ has no member named ‘name_length’
> 
> /tmp/pear/install/runkit/php_runkit.h:463:26: error: ‘zend_class_entry’ has no member named ‘name_length’
> 
> /tmp/pear/install/runkit/php_runkit.h:463:26: error: ‘zend_class_entry’ has no member named ‘name_length’
> 
> /tmp/pear/install/runkit/php_runkit.h:463:26: error: ‘zend_class_entry’ has no member named ‘name_length’
> 
> /tmp/pear/install/runkit/php_runkit.h:463:26: error: ‘zend_class_entry’ has no member named ‘name_length’
> 
> /tmp/pear/install/runkit/php_runkit.h:464:57: error: ‘zend_class_entry’ has no member named ‘name_length’
> 
> /tmp/pear/install/runkit/php_runkit.h:464:3: error: passing argument 2 of ‘zend_str_tolower_copy’ from incompatible pointer type [-Werror]
> 
> /home/travis/.phpenv/versions/7.0.4/include/php/Zend/zend_operators.h:341:37: note: expected ‘const char *’ but argument is of type ‘struct zend_string *’
> 
> /tmp/pear/install/runkit/php_runkit.h: In function ‘php_runkit_parse_doc_comment_arg’:
> 
> /tmp/pear/install/runkit/php_runkit.h:540:3: error: implicit declaration of function ‘Z_TYPE_PP’ [-Werror=implicit-function-declaration]
> 
> /tmp/pear/install/runkit/php_runkit.h:541:4: error: implicit declaration of function ‘Z_STRVAL_PP’ [-Werror=implicit-function-declaration]
> 
> /tmp/pear/install/runkit/php_runkit.h:541:18: error: assignment makes pointer from integer without a cast [-Werror]
> 
> /tmp/pear/install/runkit/php_runkit.h:542:4: error: implicit declaration of function ‘Z_STRLEN_PP’ [-Werror=implicit-function-declaration]
> 
> /tmp/pear/install/runkit/php_runkit.h: In function ‘php_runkit_parse_args_to_zvals’:
> 
> /tmp/pear/install/runkit/php_runkit.h:557:2: error: passing argument 2 of ‘_zend_get_parameters_array_ex’ from incompatible pointer type [-Werror]
> 
> /home/travis/.phpenv/versions/7.0.4/include/php/Zend/zend_API.h:250:14: note: expected ‘struct zval *’ but argument is of type ‘struct zval ***’
> 
> /tmp/pear/install/runkit/php_runkit.h: In function ‘php_runkit_parse_function_arg’:
> 
> /tmp/pear/install/runkit/php_runkit.h:571:2: error: implicit declaration of function ‘zend_get_class_entry’ [-Werror=implicit-function-declaration]
> 
> /tmp/pear/install/runkit/php_runkit.h:571:94: error: comparison between pointer and integer [-Werror]
> 
> /tmp/pear/install/runkit/php_runkit.h:577:14: error: assignment makes pointer from integer without a cast [-Werror]
> 
> /tmp/pear/install/runkit/php_runkit.h:583:12: error: assignment makes pointer from integer without a cast [-Werror]
> 
> /tmp/pear/install/runkit/php_runkit.h: At top level:
> 
> /tmp/pear/install/runkit/php_runkit.h:654:3: error: unknown type name ‘zend_uint’
> 
> /tmp/pear/install/runkit/php_runkit.h:655:3: error: unknown type name ‘zend_uint’
> 
> /tmp/pear/install/runkit/php_runkit.h:687:1: error: unknown type name ‘zend_object_store_bucket’
> 
> /tmp/pear/install/runkit/php_runkit.h: In function ‘php_runkit_zend_object_store_get_obj’:
> 
> /tmp/pear/install/runkit/php_runkit.h:689:2: error: unknown type name ‘zend_object_handle’
> 
> /tmp/pear/install/runkit/php_runkit.h:690:2: error: return from incompatible pointer type [-Werror]
> 
> /tmp/pear/install/runkit/runkit.c: In function ‘zif_runkit_superglobals’:
> 
> /tmp/pear/install/runkit/runkit.c:40:3: error: passing argument 2 of ‘zend_hash_get_current_key_ex’ from incompatible pointer type [-Werror]
> 
> /home/travis/.phpenv/versions/7.0.4/include/php/Zend/zend_hash.h:168:30: note: expected ‘struct zend_string **’ but argument is of type ‘char **’
> 
> /tmp/pear/install/runkit/runkit.c:40:3: error: passing argument 3 of ‘zend_hash_get_current_key_ex’ from incompatible pointer type [-Werror]
> 
> /home/travis/.phpenv/versions/7.0.4/include/php/Zend/zend_hash.h:168:30: note: expected ‘zend_ulong *’ but argument is of type ‘uint *’
> 
> /tmp/pear/install/runkit/runkit.c:40:3: error: passing argument 4 of ‘zend_hash_get_current_key_ex’ from incompatible pointer type [-Werror]
> 
> /home/travis/.phpenv/versions/7.0.4/include/php/Zend/zend_hash.h:168:30: note: expected ‘HashPosition *’ but argument is of type ‘ulong *’
> 
> /tmp/pear/install/runkit/runkit.c:40:3: error: too many arguments to function ‘zend_hash_get_current_key_ex’
> 
> /home/travis/.phpenv/versions/7.0.4/include/php/Zend/zend_hash.h:168:30: note: declared here
> 
> /tmp/pear/install/runkit/runkit.c:40:91: error: ‘HASH_KEY_NON_EXISTANT’ undeclared (first use in this function)
> 
> /tmp/pear/install/runkit/runkit.c:40:91: note: each undeclared identifier is reported only once for each function it appears in
> 
> /tmp/pear/install/runkit/runkit.c:43:4: error: too many arguments to function ‘add_next_index_stringl’
> 
> /home/travis/.phpenv/versions/7.0.4/include/php/Zend/zend_API.h:433:14: note: declared here
> 
> /tmp/pear/install/runkit/runkit.c: In function ‘zif_runkit_zval_inspect’:
> 
> /tmp/pear/install/runkit/runkit.c:65:62: error: macro "add_assoc_stringl" passed 5 arguments, but takes just 4
> 
> /tmp/pear/install/runkit/runkit.c:65:2: error: ‘add_assoc_stringl’ undeclared (first use in this function)
> 
> /tmp/pear/install/runkit/runkit.c:67:2: error: ‘zval’ has no member named ‘refcount__gc’
> 
> /tmp/pear/install/runkit/runkit.c:68:2: error: ‘zval’ has no member named ‘is_ref__gc’
> 
> /tmp/pear/install/runkit/runkit.c:70:2: error: ‘zval’ has no member named ‘type’
> 
> /tmp/pear/install/runkit/runkit.c:56:6: error: variable ‘addr_len’ set but not used [-Werror=unused-but-set-variable]
> 
> /tmp/pear/install/runkit/runkit.c: In function ‘_php_runkit_init_stub_function’:
> 
> /tmp/pear/install/runkit/runkit.c:175:34: error: assignment from incompatible pointer type [-Werror]
> 
> /tmp/pear/install/runkit/runkit.c: In function ‘_php_runkit_feature_constant’:
> 
> /tmp/pear/install/runkit/runkit.c:228:9: error: assignment from incompatible pointer type [-Werror]
> 
> /tmp/pear/install/runkit/runkit.c:229:3: error: ‘zend_constant’ has no member named ‘name_len’
> 
> /tmp/pear/install/runkit/runkit.c: In function ‘php_runkit_register_auto_global’:
> 
> /tmp/pear/install/runkit/runkit.c:332:2: error: passing argument 2 of ‘zend_hash_exists’ from incompatible pointer type [-Werror]
> 
> /home/travis/.phpenv/versions/7.0.4/include/php/Zend/zend_hash.h:159:34: note: expected ‘struct zend_string *’ but argument is of type ‘char *’
> 
> /tmp/pear/install/runkit/runkit.c:332:2: error: too many arguments to function ‘zend_hash_exists’
> 
> /home/travis/.phpenv/versions/7.0.4/include/php/Zend/zend_hash.h:159:34: note: declared here
> 
> /tmp/pear/install/runkit/runkit.c:341:7: error: passing argument 1 of ‘zend_register_auto_global’ from incompatible pointer type [-Werror]
> 
> /home/travis/.phpenv/versions/7.0.4/include/php/Zend/zend_compile.h:773:14: note: expected ‘struct zend_string *’ but argument is of type ‘char *’
> 
> /tmp/pear/install/runkit/runkit.c:341:7: error: too many arguments to function ‘zend_register_auto_global’
> 
> /home/travis/.phpenv/versions/7.0.4/include/php/Zend/zend_compile.h:773:14: note: declared here
> 
> /tmp/pear/install/runkit/runkit.c:344:3: error: passing argument 2 of ‘zend_hash_find’ from incompatible pointer type [-Werror]
> 
> /home/travis/.phpenv/versions/7.0.4/include/php/Zend/zend_hash.h:154:30: note: expected ‘struct zend_string *’ but argument is of type ‘char *’
> 
> /tmp/pear/install/runkit/runkit.c:344:3: error: too many arguments to function ‘zend_hash_find’
> 
> /home/travis/.phpenv/versions/7.0.4/include/php/Zend/zend_hash.h:154:30: note: declared here
> 
> /tmp/pear/install/runkit/runkit.c:359:71: error: macro "zend_hash_next_index_insert" passed 4 arguments, but takes just 2
> 
> /tmp/pear/install/runkit/runkit.c:359:3: error: ‘zend_hash_next_index_insert’ undeclared (first use in this function)
> 
> /tmp/pear/install/runkit/runkit.c: In function ‘php_runkit_superglobal_dtor’:
> 
> /tmp/pear/install/runkit/runkit.c:417:2: error: passing argument 2 of ‘zend_hash_del’ from incompatible pointer type [-Werror]
> 
> /home/travis/.phpenv/versions/7.0.4/include/php/Zend/zend_hash.h:146:28: note: expected ‘struct zend_string *’ but argument is of type ‘char *’
> 
> /tmp/pear/install/runkit/runkit.c:417:2: error: too many arguments to function ‘zend_hash_del’
> 
> /home/travis/.phpenv/versions/7.0.4/include/php/Zend/zend_hash.h:146:28: note: declared here
> 
> /tmp/pear/install/runkit/runkit.c: In function ‘zm_deactivate_runkit’:
> 
> /tmp/pear/install/runkit/runkit.c:436:3: error: passing argument 2 of ‘zend_hash_apply’ from incompatible pointer type [-Werror]
> 
> /home/travis/.phpenv/versions/7.0.4/include/php/Zend/zend_hash.h:132:29: note: expected ‘apply_func_t’ but argument is of type ‘int (*)(void *)’
> 
> /tmp/pear/install/runkit/runkit.c:446:3: error: passing argument 2 of ‘zend_hash_apply’ from incompatible pointer type [-Werror]
> 
> /home/travis/.phpenv/versions/7.0.4/include/php/Zend/zend_hash.h:132:29: note: expected ‘apply_func_t’ but argument is of type ‘int (*)(void *)’
> 
> /tmp/pear/install/runkit/runkit.c:454:154: error: expected expression before ‘)’ token
> 
> /tmp/pear/install/runkit/runkit.c:454:154: error: passing argument 2 of ‘zend_hash_apply_with_arguments’ from incompatible pointer type [-Werror]
> 
> /home/travis/.phpenv/versions/7.0.4/include/php/Zend/zend_hash.h:134:29: note: expected ‘apply_func_args_t’ but argument is of type ‘int (*)(void *, int,  struct __va_list_tag *, struct zend_hash_key *)’
> 
> /tmp/pear/install/runkit/runkit.c:464:18: error: initialization from incompatible pointer type [-Werror]
> 
> /tmp/pear/install/runkit/runkit.c:467:4: error: implicit declaration of function ‘ALLOC_ZVAL’ [-Werror=implicit-function-declaration]
> 
> /tmp/pear/install/runkit/runkit.c:468:24: error: lvalue required as left operand of assignment
> 
> /tmp/pear/install/runkit/runkit.c:469:4: error: implicit declaration of function ‘Z_SET_REFCOUNT_PP’ [-Werror=implicit-function-declaration]
> 
> cc1: all warnings being treated as errors
> 
> make: *** [runkit.lo] Error 1
> 
> ERROR: `make' failed`

**Comment by FastLizard4** [comment]
Entirely an upstream issue.  See zenovich/runkit#87.

**Comment by stwalkerster** [comment]
Related: https://techblog.badoo.com/blog/2016/03/14/how-badoo-saved-one-million-dollars-switching-to-php7/

**Comment by FastLizard4** [comment]
Holy shit.
