### ISSUE TITLE
Explore alternatives to runkit for PHP7

### ISSUE THREAD

**Issue by Matthewrbowker** [enwikipedia-acc/waca#254]
Currently, runkit isn't working for PHP7 (See #253).  If runkit isn't upgraded, we need to explore alternatives.  

Filling this here as a tracking task, this is very low priority and can be closed if runkit is upgraded.

**Comment by stwalkerster** [comment]
Prod is now PHP7.3, so all builds are failing now.

**Comment by stwalkerster** [comment]
runkit7 is a thing, we should move to that.

**Comment by stwalkerster** [comment]
actually, gonna close this as a dupe of #262
