### ISSUE TITLE
Ability to ban users by user agent

### ISSUE THREAD

**Issue by Matthewrbowker** [enwikipedia-acc/waca#258]
Possibility to ban users by their user agent.

Concerns with implementation, as the privacy policy has changed.  

Tagged with newinternal, as it would probably be implemented in newinternal.

**Comment by dqwiki** [comment]
Removing from new internal, as we are too close to implementation. This needs explaining and a use case, as Matthew states has privacy implications.

**Comment by stwalkerster** [comment]
Adding back to newinternal project as there's no way in hell this is getting implemented in master.

**Comment by dqwiki** [comment]
I have never seen a need for this. Also hasn't been commented on in heading on 3 years. Reopen if this still has a valid need.
