### ISSUE TITLE
Ability for admins to manually confirm account requests

### ISSUE THREAD

**Issue by Matthewrbowker** [enwikipedia-acc/waca#259]
Sometimes, users will reply to the email list rather than clicking the confirm link.  It would be useful for tool admins to be able to manually confirm these account requests rather than directing the user to jump through more hoops.  

Tagged wishlist and needs discussion.  

Prompted by https://lists.wikimedia.org/mailman/private/accounts-enwiki-l/2016-March/019610.html

**Comment by FastLizard4** [comment]
Doesn't sound like something that would be too difficult to do.  I don't think we should bother trying to list every unconfirmed request - maybe allow searching of unconfirmed requests by email and/or request ID, then allowing manual confirmation from there?

**Comment by Matthewrbowker** [comment]
Yes.  Or just allow viewing of a request by URL only?  After all, we already have the ID from the subject.

**Comment by FastLizard4** [comment]
Well, I'm thinking we may not necessarily, such as the instances when someone just emails the list with a subject like "confirm" and a blank body - in that case, we'd only have the email address to go on.

**Comment by stwalkerster** [comment]
If they just hit reply and said confirm, we have the email below so anyone
can click on that link currently.

Otherwise, yeah, search by email (add a search parameter to the search
form) and add a mark confirmed button into /viewRequest somewhere. This
will need a confirmation option, and will need to be logged as being
performed by the relevant user rather than by the requestor, and the IRC
notification will need to be updated as well.

Related, bin the email confirm setting, and add an outbound email null
route option, disabling all outbound mail since that is the most common
issue for development and the reason that flag still exists. Would simplify
the workflow significantly too.

**Comment by stwalkerster** [comment]
I'm going to suggest we take the following approach to this:

* Add a checkbox to show unconfirmed requests to the search results (will likely need a refactoring of the search page to allow multiple conditions - SearchHelper infrastructure will be useful for this)
* Change the restriction on viewing unconfirmed requests to have a button to manually mark it as confirmed, with a big nasty warning second-step reminding folk why we have email confirmation and to be doubly sure this is valid before continuing
* Log manual confirmations, and ping IRC
* Add a restricted stats page which lists all unconfirmed requests (ID, username, email) for those especially-hard-to-find instances
* Remove the ability to turn off email confirmation from a tool development perspective

Opinions @FastLizard4 @Matthewrbowker ? I think if we can do this, it's an easy task for someone to complete, albeit a larger change.

**Comment by Matthewrbowker** [comment]
I know this comment is 5!! years old, but I think this is a good approach.  Any objections to me taking a crack at it?

**Comment by stwalkerster** [comment]
None from me :)

I'd advise taking a look at the search PR (#560) I raised a while back that's kinda languished - that is probably a better base for the search page based bits of this, though it will need work to bring it up-to-date with everything that's happened since.

**Comment by stwalkerster** [comment]
OK, so I rebased and fixed the aforementioned search PR, and it's now #751 rather than #560 if you want to use it as a baseline.
