### ISSUE TITLE
"Disable automatic welcoming" should always be available

### ISSUE THREAD

**Issue by Matthewrbowker** [enwikipedia-acc/waca#261]
Right now, it's unclear when a user has welcoming disabled.  It would be helpful to always display the option to "disable automatic welcoming" even if the user has selected it.

**Comment by stwalkerster** [comment]
Simple case of removing the if statement from the `<tfoot>` of `templates/welcome-template/list.tpl`

@Matthewrbowker - do you have code for this already, or is this something a newbie could pick up? It's been assigned to you for over a year :)

**Comment by Matthewrbowker** [comment]
@stwalkerster Erm... I honestly don't remember what this task is - I was holding off until newinternal was done but...
