### ISSUE TITLE
Prepare tests for php7

### ISSUE THREAD

**Issue by Matthewrbowker** [enwikipedia-acc/waca#262]
What is says on the tin.  We need to prepare our tests for an eventual move to php7

**Comment by stwalkerster** [comment]
This should be just a case of upgrading to `runkit7`, but "should" and "are" are two different beasts

**Comment by mdaniels5757** [comment]
I actually did this, hold up.

**Comment by stwalkerster** [comment]
Oooh, excellent. I was planning on attacking this in the near future, if you've managed to save me some work I'll be quite happy :)
