### ISSUE TITLE
Log Viewer: Searchable actions issues

### ISSUE THREAD

**Issue by RileyHuntley** [enwikipedia-acc/waca#269]
Searchable actions for log viewer does not include **dropped request** and has two options for **edited a comment**

**Comment by stwalkerster** [comment]
Editing comments creates two log entries, one tied to the comment and one tied to the request - this is to make it much easier to show log entries for requests, as well as to log which specific comment was edited. See the difference between https://accounts.wmflabs.org/acc.php?action=logs&filterAction=EditComment-r  and https://accounts.wmflabs.org/acc.php?action=logs&filterAction=EditComment-c . It probably should be clearer from the UI what each means, but hey.

"Closed*" log actions are automatically generated from the email templates, looks like we forgot about dropped requests (and possibly custom closes) from that interface.

Relevant area of code - same bug is in both branches:
* master: https://github.com/enwikipedia-acc/waca/blob/master/includes/Helpers/Logger.php#L411
* newinternal: https://github.com/stwalkerster/waca/blob/newinternal/includes/Helpers/LogHelper.php#L176

Workaround for dropped is to use this link: https://accounts.wmflabs.org/acc.php?action=logs&filterAction=Closed+0
