### ISSUE TITLE
Ready system for developers and testers

### ISSUE THREAD

**Issue by dqwiki** [enwikipedia-acc/waca#27]
Currently the ACC system has many files, some of them non-public, that are required for setting up the ACC system out of the box. This bug aims to get the ACC system ready for out of the box setup and working properly. It will allow testers to try out the system at home without technical constraints and allow developers to test at home/offline, and without submitting 10 million commits :P

**Comment by stwalkerster** [comment]
OAuth documentation added to INSTALLING.md, using our OAuth wiki on labs.

**Comment by stwalkerster** [comment]
Actually, what else do we need to do to make this friendly enough for mere mortals? :grinning:
