### ISSUE TITLE
AntiSpoof results:  Unrecognised API response

### ISSUE THREAD

**Issue by DocTree** [enwikipedia-acc/waca#275]
On requests being processed on 17 Oct, the AntiSpoof results:  shows "Unrecognised API response to query."  Pink horizontal highlight bar, red text.  Tool overall performance is unusually slow but everything else seems to be working.

**Comment by Matthewrbowker** [comment]
I suspect it's related to https://phabricator.wikimedia.org/T146451 - Some of the API machines are returning 503 errors.

**Comment by FastLizard4** [comment]
Yeah, this does indeed seem to be an upstream API issue.  Nothing really to be done by us, so closing this for now but we'll continue to monitor the situation.
