### ISSUE TITLE
Pull in popper.js as a dependency somehow

### ISSUE THREAD

**Issue by Matthewrbowker** [enwikipedia-acc/waca#276]
We should convert the lib directory to composer.  For example:
- https://packagist.org/packages/twbs/bootstrap
- https://packagist.org/packages/mediawiki/oauthclient

**Comment by stwalkerster** [comment]
I need to double-check what still needs to be done on this in newinternal

**Comment by stwalkerster** [comment]
Only popper.js is missing now, the rest has been done as part of newinternal.

There's no composer packages for popper.js though, so we either keep this bundled or think of another way of doing it.

**Comment by stwalkerster** [comment]
I'm not looking to work on this any time soon, partly because I don't know how to approach it sanely. I'm not hugely enthusiastic about adding another package manager, but if that is what is needed, so be it.

**Comment by stwalkerster** [comment]
Pulling this into H1 2021, since the WebAuthn work is likely to require npm/yarn as well, we might as well close this one out at the same time.
