### ISSUE TITLE
Requestor emails split

### ISSUE THREAD

**Issue by stwalkerster** [enwikipedia-acc/waca#31]
Sometimes, requestor emails are split either errorneously or correctly (after being input errornously), causing issues with the toolserver's or PHP's mailer.

For example, the address `a;b@stwalkerster.co.uk`

Currently, this gets split into `a` and `b@stwalkerster.co.uk`, which is then expanded to `a@toolserver.org` and `b@stwalkerster.co.uk`. A confirmation email is then sent to _both_ addresses, both will inevitably bounce.

The solution to this is either to ensure addresses like this are not split, or to trigger an error on the user interface.

[Imported from JIRA:ACC-252]

**Comment by Matthewrbowker** [comment]
According to https://en.wikipedia.org/wiki/Email_address#Local_part, the ; is a restricted character.  Using a valid email with this ; will cause problems.

**Comment by stwalkerster** [comment]
Already resolved for users with modern browsers due to use of `<input type="email">` on the request form.

With the resolution of #439, this will also be resolved for old browsers for newinternal, as we use PHP's validation to kill invalid email addresses such as this.

As such, closing the last JIRA-imported bug, more than four years after it was migrated! \o/
