### ISSUE TITLE
Get rid of the "invalid checksum" error on refreshing a "done" page

### ISSUE THREAD

**Issue by Manishearth** [enwikipedia-acc/waca#36]
![image](https://f.cloud.github.com/assets/1617736/406204/95efef46-aa6a-11e2-9bff-c8f914394a86.png)

We've all seen that happen, right? After completing a request one refreshes the page, getting this error.

However, this can be easily fixed. With a bit of JavaScript we can manipulate the URL without having to reload the page, effectively getting rid of the query string (so if the user refreshes the page, they get the ACC main page instead of the checksum page)

```
history.pushState({},document.title,"acc.php")
```

(I don't have sand access right now so I'm not making changes)

A more elegant solution would be to switch to POST, but that would take a while.

**Comment by stwalkerster** [comment]
Fixed in #232
