### ISSUE TITLE
TTFB lag extremely high on users.php

### ISSUE THREAD

**Issue by dqwiki** [enwikipedia-acc/waca#417]
The TTFB takes about 20 seconds when loading the user management page. Either something is extremely wrong, or something has not been optimized.

![screenshot 36](https://cloud.githubusercontent.com/assets/676350/22957551/08a16b72-f2f7-11e6-8af2-90182a771b49.jpg)

**Comment by stwalkerster** [comment]
Every time the user's onwikiname is shown, a check is done against the value from the OAuth identity token - if that token has expired, it is reloaded from Wikipedia.

This is mostly transparent - it adds around half a second to page load times in almost all cases. For user management though, we have to refresh this for every user in the same request.

I've had a look at this multiple times, and come to the conclusion that it needs a fair amount of work to refactor and change how we're handling oauth tokens such that we're happy to use an expired identity ticket. Unfortunately there's a tradeoff here - the identity ticket tells us if a user is blocked or not.

**Comment by cyberpower678** [comment]
Multicurl?

Gesendet von Maximilian's iPhone. 
(Sent from Maximilian's iPhone.)

**Comment by stwalkerster** [comment]
@cyberpower678 I'd rather not - API etiquette is [to do serial requests](https://www.mediawiki.org/wiki/API:Etiquette), so I'd rather stick to that where possible.

I'd like to move all of the OAuth code out of the User objects - it really doesn't belong there - and then use helper methods to either update the OAuth identity ticket or use cached data where it doesn't matter so much. This will probably be a case of always refreshing the ticket on login, plus a configurable maximum allowed time in tool configuration (probably 15 mins or something), such that the ticket is refreshed on an action by that user every 15 minutes while logged in. Looking at the current tickets issued by MediaWiki, they're only valid for 100 seconds - see this snippet from my current identity ticket on production:
```
    "exp": 1487165528,
    "iat": 1487165428,
```

Every other usage apart from the login and 15-minutely ticket refresh while logged in should use the cached data.

This is a pretty significant refactor, so I really don't want to do this in the master branch - it's not a simple fix.

**Comment by cyberpower678** [comment]
This is similar to what my IABot tool does on tool labs.  It caches all OAuth data of the user and occasionally refreshes during the session.  Given that tool labs force ends the session in 5 minutes or so of no use, the OAuth refreshing of data isn’t really an issue.  Interface users are blocked if they’re blocked on the respective wiki.

**Comment by stwalkerster** [comment]
I'm tempted to add a global refresh to the overnight jobs to just make sure we stay roughly up-to-date with things like renames, and when people revoke the app we can mark the credentials as revoked, and stuff like that.

In any case, the issue isn't the speed at which we do the refreshes on user management, it's the fact we do them at all.

**Comment by cyberpower678** [comment]
Renames shouldn’t be an issue.  It should also be included in the refresh when the user logs in.

**Comment by stwalkerster** [comment]
I'm thinking more the case of users who haven't logged in for a while
actually.
