### ISSUE TITLE
StatsMonthlyStats.php does not open

### ISSUE THREAD

**Issue by DatGuy1** [enwikipedia-acc/waca#454]
Error as pasted by stwalkerster on IRC: 

`[Fri Jun 30 16:28:57.736629 2017] [:error] [pid 28597] [client 10.68.21.68:5764] PHP Fatal error:  require_once(): Failed opening required '/srv/production/graph/pChart/pChart.class' (include_path='.:/usr/share/php:/usr/share/pear') in /srv/production/includes/statistics/StatsMonthlyStats.php on line 37, referer: https://accounts.wmflabs.org/statistics.php`

Page is https://accounts.wmflabs.org/statistics.php/MonthlyStats

**Comment by stwalkerster** [comment]
Dealt with by disabling graph drawing in configuration.

This should be ripped out at some point and replaced, but that can happen in newinternal at some point.
