### ISSUE TITLE
Implement Global Block Flagging

### ISSUE THREAD

**Issue by Dane2007** [enwikipedia-acc/waca#464]
Still forming...a few ideas for this though:
(1) Display Global Block Status and Instructions if global block detected
(2) Autoclose Requests submitted when a process verifies whether a global block is currently active
(3) Apply a special flag to globally blocked requests either via a new queue or an icon to allow a user to identify the status.

@stwalkerster made a good point on number two, where this could cause an issue if a user had additional questions or the technology went haywire.  Leaning more towards #1 or #3 for this idea.

**Comment by Mdann52** [comment]
Accidental tag, apologies

**Comment by dqwiki** [comment]
The problem with this is IPv6 exists now, and we don't serve anything through IPv6 (and likely won't for the longest time). Therefore the autochecking of the IP the request is coming from is not a good determination of request validity in the first place.

**Comment by stwalkerster** [comment]
TBH, I think it is is probably redundant in favour of #425 - that will provide a way of flagging up whether global blocks exist on the request IP. Sure, it doesn't detect IPv6, but given we have no way of detecting IPv6 anyway at the moment, I think that point is moot. On that note, I have some ideas about a way to grab the IPv6 address from JS, but that's best saved for another ticket.

**Comment by stwalkerster** [comment]
Closing in favour of #425
