### ISSUE TITLE
Flagging request where email is not a common domain

### ISSUE THREAD

**Issue by samtarling** [enwikipedia-acc/waca#469]
An indicator of some sort should be present to highlight the fact the email address of the request is not from a common webmail provider (gmail, yahoo, hotmail)

This could help alert reviewers to the fact they could be dealing with a COI request

**Comment by Dane2007** [comment]
Can you expand upon exactly what you're looking for here?  I'm curious if you want the indicator on the request zoom page or on the list of Open Requests.  Also, are you looking for some sort of an icon?

I don't see a problem implementing this at all, though with the number of requests that we get with other types of email addresses it may not be very effective.

**Comment by FastLizard4** [comment]
When I saw this feacher request, the first thing that came to mind is something like the "Flags" column used by the [Tor Atlas](https://atlas.torproject.org), as an example, it's the column to the right of the IP address in this screenshot:

![image](https://user-images.githubusercontent.com/623117/31316491-84dcc16e-abe3-11e7-9e20-27adad7ca125.png)

Each icon relates to a particular attribute of the Tor node (the lightning bolt icon on the left indicates that my node is considered "fast", for example), and hovering over the icons with your mouse gives some quick information about what the icon means.

I was thinking we could do something similar on the list of open requests, for flags like "Uncommon email server", "previously deferred" (#472), or indeed any of the other attributes proposed as possible filters (#470).

**Comment by samtarling** [comment]
@FastLizard4 covers my expectations rather well, and it would help keep the UI uncluttered (icons for each of the above)

**Comment by dqwiki** [comment]
This also helps CheckUsers when running school IPs, knowing if they need to tell them to go home or allow creation. So +1

**Comment by stwalkerster** [comment]
There's a whitelist of email providers in the reporting scripts I've got, I don't see why that couldn't be reused here. Integration of those reporting scripts is mostly covered in #425
