### ISSUE TITLE
Add a link to https://browscap.org/ua-lookup (or similar) next to UA on zoom

### ISSUE THREAD

**Issue by samtarling** [enwikipedia-acc/waca#471]
On the zoom page, next to the UA listing a link to https://browscap.org/ua-lookup (or similar) would be useful.

Bonus points if you can use `browscap.ini`/`get_browser` to display little icons for OS (windows flag/android icon) for _at a glance_ infos

**Comment by stwalkerster** [comment]
Alternative suggestion from @samtarling - http://useragentstring.com/pages/api.php

Browscap.org don't have an API, their web-based check tool has CSRF protection, and requires a POST, meaning we can't include it via the `redir.php` script as a normal check. They do have datafiles we might be able to keep a local copy of for querying though

**Comment by stwalkerster** [comment]
[`get_browser()`](https://secure.php.net/get_browser) uses the browscap.org .ini file and takes a user_agent as a string parameter.

This will need work on newinternal too though, but I doubt it'll be too hard to implement there too if this works.

We can just do text stuff for now or grab http://fontawesome.io/ for some icons (just dump the css and woff files into our `lib/` directory, we can deal with linking it via composer in newinternal). You'll need to [link FA's stylesheet](http://fontawesome.io/get-started/#download-css) in `templates/header-internal.tpl` to use them, and you should be able to use them [like this](http://fontawesome.io/examples/) - have some [brand icons](http://fontawesome.io/icons/#brand)

You'll need to call the aforementioned function in zoompage.php and pass the result to the relevant template for display.

**Comment by Dane2007** [comment]
Looking this over i'm not comfortable with the complexity of this job at this time so i'm going to remove myself for someone else to work on it.

**Comment by dqwiki** [comment]
I have an objection to adding either of these services. The amount of data available, particularly with useragentstring.com is crap, it can not identify half of the extra fields on devices today and I usually have to go look them up by hand on google. Taking a look at browscap, it seems to know less when I check my computer and phone on it. It can not even identify the device that my phone is, despite it being directly in the useragent. It just comes up with "generic phone".

I would rather CUs come to the experienced ones to understand what exactly things mean.

**Comment by FastLizard4** [comment]
@dqwiki Would you say that adding these would actually be harmful, or just not necessarily useful in all cases?  If the latter, I would be tempted to add it if some people find it useful.

**Comment by dqwiki** [comment]
More harmful than helpful for checkusers. There are points where you have to get very specific with useragents, and it could be the smallest difference that these systems would not pick up. Fail to pick up one of those, someone could get a drop or block target message inadvertently. Much rather they learn manually how to interpret UAs or a guide get posted to CU wiki than using these tools.

**Comment by FastLizard4** [comment]
Alright then, fair enough
