### ISSUE TITLE
Sort by request time gives mixed results

### ISSUE THREAD

**Issue by samtarling** [enwikipedia-acc/waca#479]
# Steps to reproduce
1. Click "Show all x requests"
2. Click the table header "Request time" until listing newest to oldest

# Expected
Requests are listed from newest to oldest

# Actual
Requests _generally_ are ordered newest to oldest, but some are not (see screengrab)

# Screengrab

![image](https://user-images.githubusercontent.com/375162/34910501-c8dd98f8-f8ae-11e7-8e0e-a7fc347d439c.png)

**Comment by stwalkerster** [comment]
This looks like this is doing a string-sort rather than a date sort. I suspect this is an upstream issue, but it's worth checking we're not doing something stupid here.

**Comment by stwalkerster** [comment]
If this is still an issue, we can fix this by setting the data sort value on the column. We just need to be smart about what sort value we create.
