### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by samtarling** [enwikipedia-acc/waca#480]
When visiting `/api.php?action=help` you're greeted with the help text `<info>Help info goes here!</info>`

Perhaps creating https://github.com/enwikipedia-acc/waca/wiki/API and linking to it there would be a little more helpful?

Happy to do this! 😺

**Comment by stwalkerster** [comment]
https://github.com/enwikipedia-acc/waca/blob/master/includes/API/Actions/HelpAction.php

👍
