### ISSUE TITLE
Move UI over to Bootstrap v4.

### ISSUE THREAD

**Issue by bardiharborow** [enwikipedia-acc/waca#484]
A minor nitpick really, but as I'm on the Bootstrap team it's a bit cringey to see v2.3.2 still in action. I'm happy to outlay the legwork here. If IE 8-9 support is critical, v3 might be a compromise.

**Comment by stwalkerster** [comment]
Legacy support is reasonably critical, but only for the front-end, not so much for the internal interface. It should be possible to use the public side with the oldest browser you can edit Wikipedia with.

Having said that, I've looked at moving to Bootstrap v3 before, but given there's been some fairly intrusive changes to the grid system (all the classes have changed, and fluid boundaries have changed), and at the time I was sure there were some features we use removed - but that seems to not be the case with v4), I gave up on looking at it as too much work for too little benefit.

If we go ahead with this, we need to be aware of our purple button styling and sortable tables, both of which are bolt-ons to the current version of Bootstrap. I'm also tempted to ditch the bootstrap styling entirely on the front-end, and switch to the OOUI CSS instead.

**Comment by Mdann52** [comment]
Hey,

I'm looking into getting some front-end experience, so I'm happy to try and put something together styling-wise if you think it will be useful!

**Comment by stwalkerster** [comment]
I'm happy for either of you (or both!) to pick this up, I'd suggest this happens based on at least the [rbac branch](https://github.com/enwikipedia-acc/waca/tree/rbac) or [stwalkerster/otp](https://github.com/stwalkerster/waca/tree/otp) though so you've got a more sane baseline to use.

Note my points above about backwards compatibility with old browsers on the public interface - these restrictions don't apply on the internal interface.

**Comment by Mdann52** [comment]
Noted - if you'd prefer, I'm happy to mock up a version based on BS4 and OOUI, and see which looks better and take it from there? (Personally, I think the front end would look better in the latter as well).

Just one final check - I'm going to use the list at [mediawiki](https://www.mediawiki.org/wiki/Compatibility#Browsers) unless there are any better suggestions! Would support need to extend back to basic, or just modern?

**Comment by stwalkerster** [comment]
I'd personally prefer the internal side remain on bootstrap simply for familiarity, but feel free to give it a go. I'd say that the frontend must be usable for the basic set listed there - if you can use the core functionality of wikipedia you should be able to use the account request system.

**Comment by FastLizard4** [comment]
@Mdann52 If you're having trouble setting up a development environment, please try using the ACC vagrant setup at https://github.com/enwikipedia-acc/vagrant, which will set up a VM fully configured to run ACC.

**Comment by Mdann52** [comment]
Now [In progress](https://github.com/Mdann52/waca/tree/refactor/bootstrap4)

**Comment by stwalkerster** [comment]
@Mdann52 at a quick glance it looks like you've based your changes so far on the `master` branch instead of either the `rbac` or `otp` branches as mentioned above?

A lot has changed in those branches compared to the code in `master` (`otp` is slightly newer than `rbac`, but not too far - both are on top of newinternal)

**Comment by Mdann52** [comment]
I did try against the rbac branch - however, there appears to be a "vendor" folder missing meaning I couldn't get it to run, with nothing mentioned in the readme against it? (Unfortunately, I'm a full stack JS dev and usually avoid PHP when I can, so I've not yet identified what I've forgotten to run to create this!)

**Comment by stwalkerster** [comment]
Yep, that's downloaded automatically by Composer

https://getcomposer.org/download/

You should be able to run "composer install" in the project folder and 
it'll go and fetch all the dependencies for you

And yes, I thought the install documentation mentioned Composer, but it 
doesn't. Sorry!

**Comment by Mdann52** [comment]
That makes sense, thanks - I'll update the documentation as I go if you like?
 
  On Fri, 6 Jul 2018 at 19:35, Simon Walker<notifications@github.com> wrote:   Yep, that's downloaded automatically by Composer

https://getcomposer.org/download/

You should be able to run "composer install" in the project folder and 
it'll go and fetch all the dependencies for you

And yes, I thought the install documentation mentioned Composer, but it 
doesn't. Sorry!

**Comment by stwalkerster** [comment]
Go for it - the best test for documentation is someone who knows little or nothing to successfully follow it :)

Add anything you think is needed
