### ISSUE TITLE
Better handling of subsequently self-created accounts

### ISSUE THREAD

**Issue by AfroThundr3007730** [enwikipedia-acc/waca#496]
In many cases, the AntiSpoof trigger on a request is due to the user creating the account themselves a day or two later. If the created account is an exact match for the account name in the request, the request could just be closed automatically. Or if we don't trust the system to always get that right, at least put a visual indicator next to the request on the request list so they can be quickly triaged by the users.

A visual indicator in the request list would also be handy for invalid names, as mentioned in #495.

**Comment by stwalkerster** [comment]
Yep, I've been testing a script which handles this (and a few other things), with the aim of integrating it into the tool itself as part of #425

I'll close this in preference to that bug.
