### ISSUE TITLE
After logging in, the user should be redirected back to the original URI

### ISSUE THREAD

**Issue by AfroThundr3007730** [enwikipedia-acc/waca#501]
If I click on a link requiring authentication while not logged in, I get redirected to the login screen. After authentication, I get dropped onto the ACC landing page, instead of the link that originally brought me there. The app should redirect to the value of the `Referer` header instead.

**Comment by AfroThundr3007730** [comment]
Furthermore, consider adding the [`Referrer-Policy`](https://scotthelme.co.uk/a-new-security-header-referrer-policy/) header. A decent value could be:

    Referrer-Policy: 'no-referrer, strict-origin-when-cross-origin'

Which would only send the origin to other sites, or no referrer if the browser doesn't understand the strict origin statement (all major ones should).

**Comment by stwalkerster** [comment]
This is already fixed in the newinternal branch

**Comment by AfroThundr3007730** [comment]
Sweet. Any timelines for when newinternal will see the light of day? :)

**Comment by dqwiki** [comment]
It all depends on code review right now.

**Comment by dqwiki** [comment]
So if this is just needing repo on newinternal, then i'm going to close it out for the time being
