### ISSUE TITLE
Implement Referrer-Policy header

### ISSUE THREAD

**Issue by AfroThundr3007730** [enwikipedia-acc/waca#502]
As I mentioned on #501, we should consider implementing the [`Referrer-Policy`](https://scotthelme.co.uk/a-new-security-header-referrer-policy/) header. A decent value could be:

    Referrer-Policy: 'no-referrer, strict-origin-when-cross-origin'

Which would only send the origin to other sites, or no referrer if the browser doesn't understand the strict origin statement (all major ones should). I know most of the sites linked to from the tool are generally trustworthy, but it doesn't hurt to have that extra layer of protection.

**Comment by stwalkerster** [comment]
Done
