### ISSUE TITLE
Create referral links to triage requests into specific queues.

### ISSUE THREAD

**Issue by jonkolbert** [enwikipedia-acc/waca#517]
As stewards we are discussing different ways we can help innocent users caught in rangeblocks - one idea floated around was to direct them to ACC using a specific link in the blocking template so they could be triaged directly to the stewards' queue for handling. 

Something like https://accounts.wmflabs.org?queue=1 /  https://accounts.wmflabs.org/stewards or something similar and having the ability to have those requests directly triaged would be quite useful.

This could potentially be extended to checkuserblocks on enwiki as well, potentially. 

----

* [ ] #604 
* [ ] #605 
* [ ] #606

**Comment by stwalkerster** [comment]
Note that there's some crossover with #281 and #532 here.

**Comment by stwalkerster** [comment]
This is split into #604, #605, and #606 as part of the multiproject work, so I'll leave this as a tracking task.

**Comment by stwalkerster** [comment]
@jonkolbert This functionality is now deployed to production; if you want a custom form to be created, let me know.
