### ISSUE TITLE
Old requests with email address expunged link together

### ISSUE THREAD

**Issue by Matthewrbowker** [enwikipedia-acc/waca#554]
On a very old request, it appears email addresses are expunged, appearing to be replaced with `Request@data`.  This has a weird side-effect of magically linking all of the requests together, as shown on [request 43 in the test environment](https://accounts-dev.wmflabs.org/rc/internal.php/viewRequest?id=43).  In addition, clicking the "search for the email domain" button returns `Error resolving hostname, it doesn't look like this domain exists."

We should probably treat the `Request@data` as a special string, disabling the "Other requests from this email address" section as well as the "Email data for hidden@data" section.  We can also disable the mailto link on the page.

**Comment by stwalkerster** [comment]
So I think this isn't actually an issue, but is just a culprit of bad data in that environment. `hidden@data` is the email address on the page you've linked, but that environment is currently configured to use `acc@toolserver.org` as the purged address, but it looks like in the past `hidden@data` was the configuration for this environment.

I've updated the config to use `hidden@data` and `127.0.0.2`, and the problem appears to have disappeared.

I'll put the config back to it's default setting, run the dataclear script to reset everything back to the defaults (which will act as a good test of the dataclear script too), and close this if the problem doesn't resurface
