### ISSUE TITLE
Allow copying from stock replies

### ISSUE THREAD

**Issue by ElHefWiki** [enwikipedia-acc/waca#561]
For non-admins, the text of the stock replies in Close Email Management is grayed out and non-selectable (and thus non-copypaste-able). If I want to start a custom message from one reply and steal language from another I have to type it in by hand. It'd be nice if I could select the text but couldn't modify it or save it or something.

**Comment by stwalkerster** [comment]
This is seemingly Firefox/IE-specific, and fairly easily fixable with BS4 pseudo-form controls and the prewrap CSS class.

I've reproduced on master with Firefox Android so far, but we ought to reproduce on newinternal too.

**Comment by ElHefWiki** [comment]
Yes, this is now working for me in all browsers I can reasonably test it on (that's IE, Edge, Chrome, and Firefox).
