### ISSUE TITLE
Make queue help messages dismissable

### ISSUE THREAD

**Issue by ElHefWiki** [enwikipedia-acc/waca#566]
Or add something to preferences to hide them, whatever works.

**Comment by stwalkerster** [comment]
While I'm in the area, I might as well pick this one up at the same time.

**Comment by stwalkerster** [comment]
No longer needs a schema change following preferences refactor

**Comment by stwalkerster** [comment]
`PageMain` is the main page of the tool, listing all the queues and the requests within them. As with all pages, the default method called in that class when the page is loaded is `main()`.

<details>
	<summary>Irrelevant but interesting information</summary>
Within `main()`, there's a call to `setupStatusSections`, `setupHospitalQueue`, and `setupJobQueue`. These functions setup the different queues for display on the main page. 

These functions add to a large array listing all of each status section's configuration, including whether a "show all" button is displayed, whether the section is a special type, and of course the help text and requests within that section
</details>

The queues are displayed via the template `mainpage/mainpage.tpl`, and inside there we call the template `mainpage/accordiongroup.tpl` to show each section in turn. This is precisely where the queue help text is displayed.

https://github.com/enwikipedia-acc/waca/blob/74230da6092f54b7b3cc7da82d82d86658b60f78/templates/mainpage/accordiongroup.tpl#L19-L21

We should add a preference - let's say `showQueueHelp`. You can pull the current value of a preference via a PreferencesManager instance and the `getPreference` method. For example, see how this is used when closing a request to decide whether to trigger a welcome user job:

https://github.com/enwikipedia-acc/waca/blob/74230da6092f54b7b3cc7da82d82d86658b60f78/includes/Pages/RequestAction/PageCloseRequest.php#L246-L259

If the preference is `null`, we should default to `true` (showing the help messages). Something like `->getPreference(...) ?? true` should work well here. You can pass the value of the preference through to the template via an `assign(...)` call, then modify the template to add the conditional check to show/hide the queue help message.

We also need to make it possible for users to change the setting. `PagePreferences` and the template `preferences/prefs.tpl` are where this should happen. As this is a boolean setting, you can use the existing `skipJsAbort` preference as an example.

One thing the existing preferences page does *not* do well is allow a default value to be specified. It may be worth adding an optional parameter to PagePreferences::assignPreference to allow a default value to be passed in. 

Note: `$defaultGlobal` determines if this is a global preference or not. As queue help will be different per-domain, we should set this to false.
