### ISSUE TITLE
Automatically Switch between Dark Mode on supported systems

### ISSUE THREAD

**Issue by Dane2007** [enwikipedia-acc/waca#576]
Once the dark mode skin is no longer experimental, there should be an option to enable automatic switching based on the system.  In macOS for instance, many websites I visit have dark mode automatically enabled for their themes when my mac is in dark mode.

Usually this is accomplished with CSS similar to what's laid out here: [https://dev.to/vasanthv/use-css-to-automatically-enable-dark-mode-in-your-web-app-based-on-system-settings-2jlp](url)

**Comment by stwalkerster** [comment]
Something like this? 174d02891be023b9bbaa3703fe6cead3378acbca

**Comment by Dane2007** [comment]
Precisely.  It looks to be pretty well supported in common browsers. https://developer.mozilla.org/en-US/docs/Web/CSS/@media

**Comment by stwalkerster** [comment]
I might as well pick this up since I've pretty much written the code anyway. This is blocked on dark-mode being moderately sane.

**Comment by Dane2007** [comment]
Is this still blocked?  Darkmode seems usable now!

**Comment by stwalkerster** [comment]
Nope! PR created.
