### ISSUE TITLE
Strange box in tab title when handling a request

### ISSUE THREAD

**Issue by Dane2007** [enwikipedia-acc/waca#582]
<img width="413" alt="Screen Shot 2020-07-16 at 9 22 09 PM" src="https://user-images.githubusercontent.com/26441280/87742695-e47e3480-c7ac-11ea-8da3-0652870e4083.png">

There is a strange box character showing up when in an active request in the tab titlebar.

**Comment by JJMC89** [comment]
I see the same box on my browser tabs in Chrome 83.0.4103.116 and Firefox 78.0.1 on Windows 10 since newinternal was deployed.

**Comment by stwalkerster** [comment]
It's supposed to be a checkbox to indicate the request state - compare with a closed/created request and a closed/not created request

**Comment by Dane2007** [comment]
It is rather confusing I think to people who aren't familiar with the intended functionality.  I would recommend we remove the "open" symbol and maintain just a rejected or accepted symbol - or change what displays for the open requests?  Although I'm not sure if there's a suitable replacement.

**Comment by stwalkerster** [comment]
Seemingly my last comment didn't make it to this page...

On 17/07/2020 20:38, stwalkerster wrote:
I don't really mind either way, whatever works :)
