### ISSUE TITLE
`edited a comment` shouldn't be added if no changes were made

### ISSUE THREAD

**Issue by DannyS712** [enwikipedia-acc/waca#608]
Steps to reproduce:
Click edit comment
Click save changes without changing anything

Expected result:
Nothing happens

Actual result:
Logged as editing a comment

**Comment by stwalkerster** [comment]
Should be trivial to add a check [somewhere here](https://github.com/enwikipedia-acc/waca/blob/master/includes/Pages/PageEditComment.php).

**Comment by DannyS712** [comment]
> Should be trivial to add a check [somewhere here](https://github.com/enwikipedia-acc/waca/blob/master/includes/Pages/PageEditComment.php).

Wouldn't have known where to start looking in this repo, since I'm not familiar with it at all, but thanks for the tip; PR submitted
