### ISSUE TITLE
Default admin account can't be used

### ISSUE THREAD

**Issue by supertassu** [enwikipedia-acc/waca#620]
The default admin account added in https://github.com/enwikipedia-acc/waca/blob/39cf15f4f7da6e11eecfc542838c5cbdae94bc1b/sql/seed/user_data.sql hasn't been touched in 6 years and doesn't even work properly anymore:

1. When following `INSTALLING.md`, MigrateToRoles.php isn't run which means that the `status` column is still `Admin` (not `Active`) and the user does not have the `user` role in the `userrole` table
2. The default password (`Admin`) is using [an unsupported version](https://github.com/enwikipedia-acc/waca/blob/7b36a512f477fe947f0826d7d8ff37264ca5aafe/includes/Security/CredentialProviders/PasswordCredentialProvider.php#L39) and it's [too weak to login](https://github.com/enwikipedia-acc/waca/blob/7b36a512f477fe947f0826d7d8ff37264ca5aafe/includes/Security/CredentialProviders/PasswordCredentialProvider.php#L70).

**Comment by stwalkerster** [comment]
:facepalm: 

With every database migration which involves dealing with production data, there's always *something* that's missed.

**Comment by stwalkerster** [comment]
@supertassu  - please can you give the updated database installation script a go from the `installation` branch, and check that you can install the system successfully? I've changed the default password to `enwpaccAdmin1!`, which more than meets the relevant length/complexity/common requirements. (See the commit description for everything I've changed :smile: :whale:)

**Comment by supertassu** [comment]
@stwalkerster It works fine now, thanks!
