### ISSUE TITLE
Prevent applications with IP address as requested username

### ISSUE THREAD

**Issue by ElHefWiki** [enwikipedia-acc/waca#624]
Since requested usernames can't be redacted currently and IP addresses (and things that look like IP addresses) are invalid usernames, requesters shouldn't be able to ask for them. I see potentially private information hanging out there publicly fairly permanently, especially given that our user stats pages actually are publicly accessible, showing (among other things) requested usernames of rejected requests.

Alternately, come up with a way to redact requested usernames if needed - that might be a better long-term idea if feasible (for the same reasons the option exists under revdel/oversight).

**Comment by stwalkerster** [comment]
Once a request has had it's private data purged, there's effectively nothing connecting that IP address to anything. I'd like to get @dqwiki 's opinion on this too, but I don't think there's a particular need to purge a lone IP address. Obviously, if the request comment has something, then that's different, but we can already redact that.

I agree that we should prevent valid IP addresses from being requested though.

**Comment by dqwiki** [comment]
As noted on IRC, there is no need to purge the IP as there is no account that will be made based on a IP username.

**Comment by stwalkerster** [comment]
This can be done as a step in the RequestValidationHelper::validateOther method, probably fairly easily if we call on `filter_var`. I'll tag this for H1 2021, but this should be fairly straight-forward if someone else wants to pick it up before then :)
