### ISSUE TITLE
Error when trying to search for rename logs

### ISSUE THREAD

**Issue by DannyS712** [enwikipedia-acc/waca#637]
Steps to reproduce:
Visit https://accounts.wmflabs.org/internal.php/logs?filterUser=&filterAction=Renamed&filterObjectType=&filterObjectId=&limit=100

Expected result:
Logs shown

Actual result:
Error ("Oops! Something went wrong!")
error ids: `de5054a435c36da28f7c9d33934e9f4a986f3367`, `e1063f753165a243aa8113e436b07997909b5d02`

**Comment by stwalkerster** [comment]
Error `de5054a435c36da28f7c9d33934e9f4a986f3367` and `e1063f753165a243aa8113e436b07997909b5d02` are both `Call to a member function getUsername() on bool`:

```
#0 /srv/production/includes/Helpers/LogHelper.php(373): Waca\Helpers\LogHelper::getObjectDescription(140, 'User', Object(Waca\PdoDatabase), Object(Waca\SiteConfiguration))
#1 /srv/production/includes/Pages/PageLog.php(66): Waca\Helpers\LogHelper::prepareLogsForTemplate(Array, Object(Waca\PdoDatabase), Object(Waca\SiteConfiguration))
#2 /srv/production/includes/Tasks/PageBase.php(102): Waca\Pages\PageLog->main()
#3 /srv/production/includes/Tasks/InternalPageBase.php(87): Waca\Tasks\PageBase->runPage()
#4 /srv/production/includes/WebStart.php(191): Waca\Tasks\InternalPageBase->execute()
#5 /srv/production/includes/WebStart.php(104): Waca\WebStart->main()
#6 /srv/production/internal.php(24): Waca\WebStart->run()
#7 {main}
```

Interestingly, user 140 doesn't exist:
```
MariaDB [production]> select username from user where id = 140;                                                                                                                                                    
Empty set (0.002 sec)
```

I suspect this is related to a manual user merge we did in the past, as there's no provision anywhere in the code for the removal of user accounts at the moment. It's likely a pretty easy fix - just some checks [here](https://github.com/enwikipedia-acc/waca/blob/master/includes/Helpers/LogHelper.php#L300) that the returned value isn't `false` much like we have in the ban or welcome template sections on above or below.
