### ISSUE TITLE
Job queue should display newest first

### ISSUE THREAD

**Issue by ElHefWiki** [enwikipedia-acc/waca#680]
Jobs in the job queue should go from newest to oldest, right now most recent jobs are at the bottom of the last page.

**Comment by stwalkerster** [comment]
This can probably be done by passing a sensible value into the [search helper](https://github.com/enwikipedia-acc/waca/tree/master/includes/Helpers/SearchHelpers), which is used on the [PageJobQueue class](https://github.com/enwikipedia-acc/waca/blob/master/includes/Pages/PageJobQueue.php#L74).

I'd suggest that this re-ordering only takes place on the "Show all" view, the ordering of oldest-to-newest on the main bit of the page is handy to know what order jobs will be run in.

Bonus points if this is an option on the search form.
