### ISSUE TITLE
"Show all" button on miser mode warning links to wrong place

### ISSUE THREAD

**Issue by stwalkerster** [enwikipedia-acc/waca#715]
When a queue is longer than the miser mode limits, a banner is displayed [with a button to show all requests](https://github.com/enwikipedia-acc/waca/blob/master/templates/mainpage/requestlist.tpl#L6-L8). This button links to the wrong place.

For reference, the header of the queue also [has a "Show all" link](https://github.com/enwikipedia-acc/waca/blob/master/templates/mainpage/accordiongroup.tpl#L12) at the right-hand side, which links to the correct place.

**Comment by Matthewrbowker** [comment]
Fixed by MTCD in 21811de04
