### ISSUE TITLE
Implement Banner Alert for Flagged Comments for ACC Admins

### ISSUE THREAD

**Issue by Dane2007** [enwikipedia-acc/waca#735]
If Flagged Comments != 0, show a banner that indicates "There are X number of flagged comments for review." (clicking will bring to that review page).  This would add a bit more visibility into this instead of manually checking that screen.

**Comment by stwalkerster** [comment]
I think I also want to throw in a status/queue column to that view; at the moment it's unclear whether a request is still open or not, and there have been several instances I've seen where potentially useful info has been purged out of the comment before the request was actually handled (especially in the case of deferrals to the CU queue where the comment contains an IPv6 address)

**Comment by stwalkerster** [comment]
Also noting that this will need some rights checks - it's probably fine to attach this to the main right which allows you to see PageListFlaggedComments.

Questions from me:
* Do we want to show this banner everywhere, or just on the main page? (I'd prefer just the main page since we go to it often enough)
* Do we want to make it dismissable, or permanently present when there are flagged comments? If dismissable, what triggers it to be re-shown?
* Do we want it to only alert when the flagged comments are on all requests, closed requests, or just purged requests?

I can write up a rough tech spec for this if someone else wants to pick this up? I wouldn't class it as "easy", but it should be fairly straight-forward with guidance.

**Comment by ElHefWiki** [comment]
Along the same lines, something I've brought up in the past is job failures sitting in the queue. Those typically sit for days before they're noticed and dealt with. Could that be rolled in with this?

**Comment by Dane2007** [comment]
> Along the same lines, something I've brought up in the past is job failures sitting in the queue. Those typically sit for days before they're noticed and dealt with. Could that be rolled in with this?

I know we have a Hospital queue, perhaps we can change the styling of it to attract more attention?

**Comment by Dane2007** [comment]
> Questions from me:
> * Do we want to show this banner everywhere, or just on the main page? (I'd prefer just the main page since we go to it often enough)
Just on the main page was my thought.
> * Do we want to make it dismissable, or permanently present when there are flagged comments? If dismissable, what triggers it to be re-shown?
Permanently present.
> * Do we want it to only alert when the flagged comments are on all requests, closed requests, or just purged requests?
Flagged comments on all requests.  Any request with flagged comments should be dealt with ASAP and unflagged upon resolution.

> I can write up a rough tech spec for this if someone else wants to pick this up? I wouldn't class it as "easy", but it should be fairly straight-forward with guidance.
I'm debating whether this is within my scope or ability.

**Comment by ElHefWiki** [comment]
> I know we have a Hospital queue, perhaps we can change the styling of it to attract more attention?

No, the hospital queue is fine. I'm talking more about things like job 6439 [https://accounts.wmflabs.org/internal.php/jobQueue/view?id=6439](linkylink) which was an autowelcome failure because the ACCer had already manually welcomed the user. That one was no big deal, but I've handled a couple of job failures that led to things that actually needed fixed (for example, autowelcoming failed because the account hadn't actually been created, or the user talk page existed already and needed to be deleted under CSD U2). Those job failures don't go to hospital, they just sit on the job queue page until someone happens to go looking for them. I've made a habit of checking it when I log in because of this.

**Comment by stwalkerster** [comment]
if we start adding lots of banners, it might lead to half the page being banners. Would a little flag on the menu item be sufficient here, such as how GitHub shows you have notifications?

![Screenshot_20220415-082045.jpg](https://user-images.githubusercontent.com/722710/163538599-fc526a91-a6ea-4245-8d00-3684a0d2d8c2.jpg)

**Comment by stwalkerster** [comment]
OK, here's a bit of a tech spec/implementation guide for this

I'll strongly advise you to have an environment to test this in as you go before you get started.

### nav bar flag for flagged comments
I think there's only three files which need to be edited:

#### `navigation-menu.tpl`
Two things to do:
- Add the icon to the dropdown item
        - Pick the icon to use from [this set](https://fontawesome.com/v5/search?m=free). 
        - introduce new variable - probably `$navalert__flaggedComments` to indicate whether to show a flag. 
        - Add an `{if}` inside the Flagged Comments `<a>` testing for the variable (around L49), showing an icon. 
        - Feel free to put the icon inside [a badge](https://getbootstrap.com/docs/4.6/components/badge/) too
        - You *may* wish to adjust the padding on the badge - [adding one of the `px-*` classes](https://getbootstrap.com/docs/4.6/utilities/spacing/) should be sufficient
- Add the icon to the dropdown itself
        - Around L28 is an `<a>` for the dropdown. Basically do the same thing as above, but here too.

#### `TemplateOutput.php` 
This is the main class which initialises template variables for the nav bar (amongst other things). We want our new variable to always be initialised to a sensible default here - probably `false`. 
- Add a new `assign()` call for our new variable there.

#### `InternalPageBase.php`
This is the base class for *all* internal pages, so changes here will impact *every* page on the internal interface, but don't let that scare you too much.
- Add a new private function to set up our new flags. Perhaps call it `setUpNavBarFlags`? You'll need to pass a `User` object and a `PdoDatabase` object as parameters.
- Call this function from the end of `finalisePage`. Pass in `$currentUser` and `$database` as the parameters.
- Setup some logic in the new function to a) check the user has access to the applicable page, and b) check the conditions for showing the flag are met. If both, run the same `assign()` we did in `TemplateOutput` but setting the value to true. If the user doesn't have access, do nothing, and if there's nothing to alert on, also do nothing
    - You can use `$this->barrierTest(RoleConfiguration::MAIN, $currentUser, PageListFlaggedComments::class)` (which returns a boolean) to test if the user has access to the Flagged Comments page.
    - You'll need a database query to check the list of flagged comments. You can either use the existing code to pull all flagged comments and all their details (easier, slower), or you can write a special one which just returns what's needed (harder, faster).
        - Easy: `Comment::getFlaggedComments($database)` returns an array of all flagged comments.
        - Hard: `select exists (select 1 from comment where flagged = 1);` is probably a good query to use - it'll return a single cell, either a 1 or 0, depending on whether there are any flagged comments or not. You can do something like `$database->query(...)->fetchColumn()` here to actually run the query.

I'm envisaging something like this:
```php
function setUpNavBarFlags (...) {
   if ($this->barrierTest(...)) {
      $exists = $database->query(...)->fetchColumn()
      if ($exists) {
          $this->assign(....)
      }
   }
}
```

### nav bar flag for job queue failures.
Basically the same as above.
- Use the same icon/badge design.
- Use a new variable (maybe `navalert__jobfailures`?)
- Edit the `{if}` on the dropdown (around L28) to test for either variable instead
- Add to the `InternalPageBase::setUpNavBarFlags` function you added before to separately test a different ACL flag (probably `PageJobQueue::class` for the third `barrierTest` parameter).
- Finding failed jobs can be done with a `JobQueueSearchHelper` - call `JobQueueSearchHelper::get($database)` to get one, then probably `->statusIn(JobQueue::STATUS_FAILED)`, and probably `->notAcknowledged()`. You can call `->getRecordCount($count)` to get the number of records. Alternatively, do a database query such as `select exists (select 1 from jobqueue where status = 'failed' and (acknowledged is null or acknowledged = 0));`

**Comment by ElHefWiki** [comment]
> if we start adding lots of banners, it might lead to half the page being banners. Would a little flag on the menu item be sufficient here, such as how GitHub shows you have notifications?

If it's just attached to the menu item, you'd still have to open up the admin menu to spot it. It's an improvement, sure, but if you're opening the menu you've probably already remembered to check those things. Could there be an icon on the menu bar itself as well? Stick a flag or number next to the menu to draw attention to it, then put flags or numbers on individual menu items that have things that need attention?

As far as banner creep goes, I get what you're saying but I was thinking it could be done something like a {{multiple issues}} template. If there's multiple things that you have access to that need addressing, you'd just see multiple bullet points or notifications within a single banner.

Another random thought I had - could they appear like a queue that needs addressing? If there are requests with failed jobs or flagged comments or whatever (and the user has access to address that issue) pop up another queue line like the hospital does now. It wouldn't actually be a queue (so I don't know how feasible that is), but we're certainly conditioned to look for requests there.

**Comment by stwalkerster** [comment]
> If it's just attached to the menu item, you'd still have to open up the admin menu to spot it. It's an improvement, sure, but if you're opening the menu you've probably already remembered to check those things. Could there be an icon on the menu bar itself as well? Stick a flag or number next to the menu to draw attention to it, then put flags or numbers on individual menu items that have things that need attention?

Yup, that's covered in my techspec above

> As far as banner creep goes, I get what you're saying but I was thinking it could be done something like a {{multiple issues}} template. If there's multiple things that you have access to that need addressing, you'd just see multiple bullet points or notifications within a single banner.

I guess that's also an option; instead of modifying the navbar/templateoutput/internalpagebase, it'd just be modifications to PageMain.php and templates/mainpage/mainpage.tpl, writing the necessary HTML (Bootstrap Alert?) and assigning in a similar way to how I discussed in InternalPageBase.

> Another random thought I had - could they appear like a queue that needs addressing?

While it's possible, it's probably also substantially more work than just adding a navbar flag or a banner. All the existing infrastructure there is intended to work as if it's receiving a set of requests; not something else.
