### ISSUE TITLE
Blacklist matches not shown

### ISSUE THREAD

**Issue by methecooldude** [enwikipedia-acc/waca#737]
May be related to #730

When a request is put in to Flagged users due to TBL hits, the BL entry is not shown anywhere and hence its difficult/impossible to determine why it was hit and if it should be overridden or not.

**Comment by ElHefWiki** [comment]
This would certainly be nice to have, but isn't this upstream? I always figured it wasn't shown on-wiki for WP:BEANS reasons (at least in part) - can we display the matches to us without displaying it to Nefarious Actors™?

**Comment by methecooldude** [comment]
@stwalkerster was under the impression that they should show up

**Comment by stwalkerster** [comment]
https://github.com/enwikipedia-acc/waca/blob/master/templates/view-request/username-section.tpl#L2 is the relevant bit of the UI for this

**Comment by methecooldude** [comment]
https://github.com/enwikipedia-acc/waca/blob/master/includes/Pages/PageViewRequest.php#L270 doesn't seem to be working as https://github.com/enwikipedia-acc/waca/blob/master/templates/view-request/main.tpl#L72 doesn't seem to trigger either

**Comment by methecooldude** [comment]
I wonder if it's a domain thing thanks to https://github.com/enwikipedia-acc/waca/blob/master/includes/Helpers/BlacklistHelper.php#L93 and hence L65 is catching and failing gracefully

**Comment by stwalkerster** [comment]
Oh, possibly. We should be logging that exception out.

There's a function we can call to log stuff like this, we use it on AntiSpoof lookups too:  https://github.com/enwikipedia-acc/waca/blob/master/includes/Validation/RequestValidationHelper.php#L297
