### ISSUE TITLE
Tool administrator-only queue?

### ISSUE THREAD

**Issue by LuK3enwiki** [enwikipedia-acc/waca#740]
I have ran into some ACC requests that required a tool ban (e.g. blatant LTA or sockpuppet abuse). Usually I ping a tool admin on IRC for a tool ban request but sometimes an admin is not around. Would it be viable to create a tool admin-only queue for requests that need a tool ban?

**Comment by DannyS712** [comment]
Just came across a ticket where this would be helpful, can a tool admin please create?

**Comment by Oshwah** [comment]
ACC Tool Admin here. This seems reasonable to me. I'll create a "Needs Tool Ban"queue so that such requests can be deferred to it.

**Comment by stwalkerster** [comment]
PR #754 created to fix :smile:

**Comment by stwalkerster** [comment]
This has been created by @Oshwah
