### ISSUE TITLE
Docker improvements

### ISSUE THREAD

**Issue by stwalkerster** [enwikipedia-acc/waca#750]
Split from comments on #749 

The Docker infrastructure should work out-of-the-box.

For this, we need (I think):
* Docker-specific configuration overrides to default things like the database settings and the AMQP settings to the containers, but allowing overrides of other (any?) settings.
* Automated configuration of the RabbitMQ instance to work with the domain targets (IMHO, this should be _any_ routing key delivered to _one_ queue, with a sensible TTL on messages in the queue so it doesn't grow indefinitely)

**Comment by FastLizard4** [comment]
Mostly a note to myself: Might be cool to also pull in a simple mail sink service into the docker-compose infra so mail can be tested in a similar fashion to RabbitMQ
