### ISSUE TITLE
Point the Centralauth button to meta

### ISSUE THREAD

**Issue by ElHefWiki** [enwikipedia-acc/waca#758]
Request to point the Centralauth check button to meta as opposed to enwiki. As I understand it they provide the same information, except that the enwiki version doesn't show that the account is globally locked while meta does. It's not often relevant for ACC checks, but I have had it come up a few times (including just now with 321424). Personally, I always use the meta version when I'm working at VRT and such for precisely this reason.

**Comment by stwalkerster** [comment]
A quick change to this file should be all that's needed here: https://github.com/enwikipedia-acc/waca/blob/master/templates/view-request/username-section.tpl
