### ISSUE TITLE
Text being translated to HTML entities

### ISSUE THREAD

**Issue by AlanM1** [enwikipedia-acc/waca#76]
In various places in ACC, non-alpha-numeric characters (e.g. &, <, >, ") are being converted to HTML entities (e.g. &amp;amp;, &amp;lt;, &amp;gt;, &amp;quot;). This presents a number of problems:
1. When re-displayed in ACC, the entities are not translated back into the characters, resulting in ugly text.
2. They are sent to clients in email that way, with no specific tagging to tell the email client to translate them (i.e. no &lt;HTML&gt; tag at the top), causing the same ugly text and breaking included links.
3. Not realizing this, if you copy the email of a previous case to a new email, the result will be duplication of some of the entity characters, making a real mess.
4. The same thing happens in Preferences with the WikiML and text signatures. Worse, if you go the preferences and make another edit and save it, the partial duplication occurs there, too.

P.S. In Preferences (and probably elsewhere), the label "Submit Query" might make sense to us database people, but not to the average user. I'd suggest correct standard functional labeling for buttons, like "Save", "Cancel", etc.

**Comment by stwalkerster** [comment]
Fixed in newinternal
