### ISSUE TITLE
Composer package upgrades

### ISSUE THREAD

**Issue by stwalkerster** [enwikipedia-acc/waca#767]
We should consider upgrading the following packages:

<details>
<summary>Semi-relevant but old information</summary>

----

- smarty/smarty => ^v4.2.0
- twbs/bootstrap => ^5.2
- fortawesome/font-awesome => ^6.2
- spomky-labs/otphp => ^v11.0
- wikimedia/common-passwords => ^v0.4
- league/commonmark => ^2.3

Some of these (`wikimedia/common-passwords`, `league/commonmark`) should be fairly straight-forward since they're used in very specific and easily-testable ways.

Others (`spomky-labs/otphp`) have security considerations, and need to be very well tested as well as ensuring existing TOTP codes work.

More still (`smarty/smarty`, `fortawesome/font-awesome`) are so ingrained into the UI of the tool that a change will require retesting pretty much every page in the tool.

Finally, `twbs/bootstrap` will have some major breaking changes, and will likely require substantial fiddling around with SCSS to do the upgrade.

----
</details>

Most of the minor upgrades will be dealt with by @dependabot. Some of the more major updates will require more work.

```[tasklist]
### General list of additional work
- [ ] https://github.com/enwikipedia-acc/waca/issues/789
- [ ] https://github.com/enwikipedia-acc/waca/issues/794
- [ ] https://github.com/enwikipedia-acc/waca/issues/797
- [ ] https://github.com/enwikipedia-acc/waca/pull/793
- [ ] https://github.com/enwikipedia-acc/waca/pull/790
- [ ] https://github.com/enwikipedia-acc/waca/pull/788
- [ ] https://github.com/enwikipedia-acc/waca/pull/787
- [ ] https://github.com/enwikipedia-acc/waca/pull/796
- [ ] https://github.com/enwikipedia-acc/waca/pull/801
- [ ] https://github.com/enwikipedia-acc/waca/pull/798
- [ ] https://github.com/enwikipedia-acc/waca/pull/799
- [ ] https://github.com/enwikipedia-acc/waca/pull/800
- [ ] https://github.com/enwikipedia-acc/waca/pull/802
- [ ] https://github.com/enwikipedia-acc/waca/pull/804
- [ ] https://github.com/enwikipedia-acc/waca/pull/795
```

**Comment by methecooldude** [comment]
font-awesome should be easy enough, the fonts haven't really changed

**Comment by dqwiki** [comment]
Would creating a PR for this help so we can at least run through the existing tests in the system plus set it up on a dev server and start seeing what's broken?

**Comment by stwalkerster** [comment]
I don't think we should put all of these in **one** pull request, but having a series of PRs we can test is fine by me.

The four groups I listed above would make a good starting point so we're not creating thousands of PRs

**Comment by stwalkerster** [comment]
So I'm basically working through this list with the assistance of dependabot. I'll update the main description with the current status.

**Comment by stwalkerster** [comment]
I'm gonna close this as Dependabot has worked it's way through everything, except the ones that have different tasks opened.
