### ISSUE TITLE
Debian and database updates to Docker config

### ISSUE THREAD

**Issue by FastLizard4** [enwikipedia-acc/waca#827]
The Docker configuration and scripts need a couple updates
- Update to Debian bookworm and PHP 8.2 (the default shipped with bookworm)
- Update the Docker database seed script to use the new syntax for the `test_db.sh` script

**Comment by stwalkerster** [comment]
Let's just update the docker image to Bookworm and use the Bookworm-default PHP (8.2 I believe), as that's the closest match to (what will be) production.

My expectation is that Prod will switch to Bookworm "imminently" (ie, as soon as we can [un-fsck our WMCS project][T342381]), so I don't think there's much point in putting any effort into maintaining 7.4 as long as we test on [rc][rc]/[demo][demo] first. My local environment (which is non-Docker) will stay on 7.4 for the time being, and I'm the most active dev so I'm likely to catch any incompatibilities anyway.

[T342381]: https://phabricator.wikimedia.org/T342381
[rc]: https://accounts-dev.wmflabs.org/rc/internal.php
[demo]: https://accounts-dev.wmflabs.org/demo/internal.php

**Comment by FastLizard4** [comment]
Hah, that's a fun Phabricator ticket.

I've confirmed that [Debian bookworm offers PHP 8.2 by default](https://packages.debian.org/bookworm/php), so I'll go ahead and get started with this.
