### ISSUE TITLE
Implement $wikiurl

### ISSUE THREAD

**Issue by JohnFLewis** [enwikipedia-acc/waca#96]
At the moment $wikiurl is a configuration setting however it is not used much (some usages occur IIRC). It might be a nice idea to change all links to use this as localisation is probably going to be a key thing know as ACC is at a stage where it could possibly by used on other wikis however hard coded URLs are a major issue.

Put as a feature, though this may be considered a bug and also may require live config changes in the future.

**Comment by stwalkerster** [comment]
So we have had two variables in the code for a while now:
```php
$mediawikiWebServiceEndpoint = "https://en.wikipedia.org/w/api.php";
$mediawikiScriptPath = "https://en.wikipedia.org/w/index.php";
```

Let's use these, 'cos I'm binning `$wikiurl`.

**Comment by stwalkerster** [comment]
Done in #232
